### ISSUE TITLE
Saltbot functions but match recording only gets character names correct

### ISSUE THREAD

**Issue by zgf2022** [synkarius/saltbot#102]
I'm on chrome 51.0.2704.106 and everything works with salt bot and i was able to import the seed data and matches but every match that the bot runs through gets a result code like this

c1:Cassius bright|c2:Nayuta|w:1|s:cs|p:t|t:U|m:m|o:U|t:0 

where the character names are correct but nothing else is (character 2 won that particular fight)
The 2nd tab the extension opened is open and logged into twitch and ive already uninstalled every extension except the chrome dev tools.

**Comment by synkarius** [comment]
A `0` indicates that character 1 won, and a `1` indicates that character 2 won. It's zero-based.
It captured betting mode (s=cs=Scientist), prediction result (p=t=true), mode (m=m=Matchmaking).

It didn't capture tier, time, or odds. That might happen if this was the first match after a reload. Was it?

**Comment by synkarius** [comment]
Also, I should say, tier, time, and odds are all basically worthless. They're recorded because I think they're interesting, but statistically, all that matters is win percentage, which is being captured correctly in your example.

Nevertheless, I would like to know if this was caused by a page refresh or not in order to determine if it's a real bug.

**Comment by zgf2022** [comment]
ah i started to suspect the zero based after i saw a few more results 

but nope on the reload
match result code: c1:Assassin|c2:Margaretha_solin|w:1|s:cs|p:f|t:U|m:m|o:U|t:0
match result code: c1:Zankuro|c2:Elpis|w:1|s:cs|p:f|t:U|m:m|o:U|t:0
match result code: c1:Remilya scarlet|c2:Mobo|w:0|s:cs|p:t|t:U|m:m|o:U|t:0
match result code: c1:Voltz|c2:Chrome dome|w:1|s:cs|p:t|t:U|m:m|o:U|t:0
match result code: c1:Scopedog-rsc|c2:Momo-len_ver1.39|w:1|s:cs|p:t|t:U|m:m|o:U|t:0
match result code: c1:Dragon EX2|c2:Zangeese EX2|w:0|s:cs|p:f|t:U|m:m|o:U|t:0
match result code: c1:Gikoneko|c2:Fygar|w:0|s:cs|p:f|t:U|m:m|o:U|t:0
match result code: c1:Qb|c2:Skapon|w:1|s:cs|p:f|t:U|m:m|o:U|t:0
match result code: c1:Wtf mizuchi|c2:Emerald|w:0|s:cs|p:t|t:U|m:m|o:U|t:0
match result code: c1:Himekawa kotone|c2:Kirakira|w:1|s:cs|p:t|t:U|m:m|o:U|t:0
match result code: c1:Sodom sfa|c2:Pokita|w:0|s:cs|p:t|t:U|m:m|o:U|t:0

and so on, heres a couple of whole blocks
`» PREDICTION STATS for (Sodom sfa VS Pokita) »
strategy.js:501 » WINS/LOSSES:     weighted totals as % (red:blue) -> (80 : 20)  ::  unweighted (red W:L)(blue W:L) -> (4:11)(1:14)  ::  details (red W:L)(blue W:L) -> (AAAA:AAAAAAAAAAA)(A:AAAAAAAASAAAAA)
strategy.js:505 » predicted odds -> (1.00 : 12916.49)  ::  avg win time (red:blue) -> (146 : 108      )  ::  avg loss time (red:blue) -> (143 : 129      )
strategy.js:510 

strategy.js:47 - betting at level: 1, confidence: 60.96
tracker.js:98 AGGRO multiplier active, increasing bet to 610
salty.js:207 - records saved, matches this cycle: 12
salty.js:134 - match result code: c1:Sodom sfa|c2:Pokita|w:0|s:cs|p:t|t:U|m:m|o:U|t:0
salty.js:196 - number of:: chars: 6295, matches: 59092, bettors: 0
strategy.js:499 

strategy.js:500 » PREDICTION STATS for (Custom 2dfm95 anne of green gables VS Dirty kf man) »
strategy.js:501 » WINS/LOSSES:     weighted totals as % (red:blue) -> (44 : 56)  ::  unweighted (red W:L)(blue W:L) -> (4:9)(5:10)  ::  details (red W:L)(blue W:L) -> (BBBB:BBUBBBBBB)(BBBBB:BBBBBBBBBB)
strategy.js:505 » predicted odds -> (1.00 : 1.13    )  ::  avg win time (red:blue) -> (203 : 130      )  ::  avg loss time (red:blue) -> (80 : 140       )
strategy.js:510 

strategy.js:47 - betting at level: 1, confidence: 71.12
tracker.js:98 AGGRO multiplier active, increasing bet to 720
salty.js:207 - records saved, matches this cycle: 13
www-cdn-jtvnw-x.js:289 Uncaught TypeError: Cannot read property 'length' of undefined(anonymous function) @ www-cdn-jtvnw-x.js:289each @ jquery-2.1.1.min.js:2success @ www-cdn-jtvnw-x.js:268j @ jquery-2.1.1.min.js:2fireWith @ jquery-2.1.1.min.js:2x @ jquery-2.1.1.min.js:4(anonymous function) @ jquery-2.1.1.min.js:4
salty.js:134 - match result code: c1:Custom 2dfm95 anne of green gables|c2:Dirty kf man|w:1|s:cs|p:t|t:U|m:m|o:U|t:0
salty.js:196 - number of:: chars: 6295, matches: 59093, bettors: 0
strategy.js:499 

strategy.js:500 » PREDICTION STATS for (Limiter cut broly VS Index ver7.26) »
strategy.js:501 » WINS/LOSSES:     weighted totals as % (red:blue) -> (91 : 9)  ::  unweighted (red W:L)(blue W:L) -> (10:1)(1:0)  ::  details (red W:L)(blue W:L) -> (XXXXXXXXXX:X)(X:)
strategy.js:505 » predicted odds -> (101.38 : 1.00  )  ::  avg win time (red:blue) -> (88 : 63        )
strategy.js:510 

strategy.js:537 -- PROBLEMS:
- insufficient information (scores: 0.77:2.09), W:L(P1)(P2)-> (10:1)(1:0), 
--> dropping confidence by 30%
strategy.js:47 - betting at level: 1, confidence: 36.26
tracker.js:98 AGGRO multiplier active, increasing bet to 370
salty.js:207 - records saved, matches this cycle: 14
salty.js:134 - match result code: c1:Limiter cut broly|c2:Index ver7.26|w:1|s:cs|p:t|t:U|m:m|o:U|t:0
salty.js:196 - number of:: chars: 6295, matches: 59094, bettors: 0
strategy.js:499 
`

**Comment by zgf2022** [comment]
there are a few of these errors

`Uncaught TypeError: Cannot read property 'length' of undefined(anonymous function) @ www-cdn-jtvnw-x.js:289each @ jquery-2.1.1.min.js:2success @ www-cdn-jtvnw-x.js:268j @ jquery-2.1.1.min.js:2fireWith @ jquery-2.1.1.min.js:2x @ jquery-2.1.1.min.js:4(anonymous function) @ jquery-2.1.1.min.js:4
salty.js:134 - match result code: c1:Lizardbuckler attack!|c2:Wai|w:1|s:cs|p:t|t:U|m:m|o:U|t:0`

But they dont appear every match and i didnt figure that was coming from saltbot

**Comment by reconman** [comment]
What does the console log on the twitch tab say?

**Comment by reconman** [comment]
The problem was that the Waifu4u chat user which announces the matches and tiers was changed from Waifu4u to WAIFU4u. Once @synkarius uploads the newest version it should work for everybody again.

Thank you for reporting the issue.

**Comment by synkarius** [comment]
That makes perfect sense. Those three were the items coming in from the chat. @reconman's fix has been uploaded and should be active within an hour.

**Comment by zgf2022** [comment]
Thanks for the quick fix!
