### ISSUE TITLE
Suggestion/help

### ISSUE THREAD

**Issue by tenkira** [synkarius/saltbot#107]
The bot has constantly been betting wrong i think it might have to do with my recorded matches but i don't want to lose my progress. also it won't bet aggressive even though i have that checked..it only works with the multiplier. Also suggestion: Add a tournament betting only button so it only bets on tournaments!

**Comment by synkarius** [comment]
If the bot has been betting wrong, that's unlucky. It should have a 63% win rate with the data provided [here](https://raw.githubusercontent.com/synkarius/saltbot/master/65k%20records%20without%20exhibitions%20June%202016.txt). Throw out or append your data and use that.

Take it from me -- I'm in the top 100 without ever using Aggro mode: you don't need aggressive betting. You just need to leave it on 24/7 for a few weeks. Don't watch it and don't change bets that seem unlikely.

The tournaments-only betting is an interesting suggestion: all gains, no risk. Might be worth putting in. However, it will likely slow down your salt accumulation.

**Comment by tenkira** [comment]
It will slow down salt accumulation but I like it because of the best part of it there is: all gains no risk

**Comment by calexil** [comment]
This can be closed
