### ISSUE TITLE
Updating Genetic Weights

### ISSUE THREAD

**Issue by Dharleth** [synkarius/saltbot#108]
How often should I update genetic weights after the initial set up as the bot records more matches over time? Also when I update genetic weights do I always need to reset the pool first? 

If I don't need to reset the pool how many new generations should I let it run for? 50 ish like the initial set up?
Thanks

**Comment by reconman** [comment]
Resetting the pool = Reverting the weights back to default

You do not have to reset the pool after you have updated the genetic weights once. The algorithm will try to find better chromosomes than the current one when you click on update genetic weights.

You should update the genetic weights once every 2 weeks or so. When you let it run and don't see any improvements in 20 generations you can stop. Then the algorithm is stuck in a local maximum and does not know how to get a better result without heavily changing the weights.

Resetting the pool could achieve getting a better maximum but it could also lead to worse performance. It all depends on the random weight changes in the genetic algorithm.
