### ISSUE TITLE
Definite/max betting amount put in by user

### ISSUE THREAD

**Issue by Otaku-2** [synkarius/saltbot#110]
It'd be helpful if the bot could have a feature that would let the user put in a definite amount for the bot to bet, be it an amount that the user puts in and the bot bets that each round, or a max amount that the bot cannot go over. This would help me as I'm just under 10k, and it seems whenever I get above, the bot starts  betting more money than it was before, putting me at a risk of losing more money (Scientist mode is selected, and it still jumps to a larger amount). The "Stop betting at xxxx amount" doesn't help as the bot just doesn't bet at all if the bet it wants to place is higher than the amount you set.

**Comment by synkarius** [comment]
The increased betting around certain thresholds is a feature. Your money will waver when you're in the process of passing a threshold, but eventually you'll get past the threshold and stay beyond it. Limiting the bot to flat amounts will just slow down gains overall.
