### ISSUE TITLE
Data not importing, no settings being saved

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#111]
this extension is completely broken on chromium.

chromosome data and records imports do nothing

monk mode records nothing

no settings are persistent

**Comment by synkarius** [comment]
Use Chrome. Chromium, Comodo Dragon, even Canary: are not supported.

**Comment by calexil** [comment]
doesnt work on chrome either man. I mean it functions a little better in that at lease(and only) the video toggle works.... nothing else does

**Comment by synkarius** [comment]
Okay, now we might have a bug. Please read the [Bugs Guide](https://github.com/synkarius/saltbot/blob/master/doc/bugs.MD) and add:
* whether you followed the troubleshooting steps
* what the console error messages are

**Comment by calexil** [comment]
ill get to it in a bit, a tournament is about to start and I found a new tool(not automated) to play with

**Comment by calexil** [comment]
okay here's what I did, and what happened.

Installed chrome(Version 55.0.2883.75 (64-bit)) since you say you 'don't support' chromium :/

set it to plain old no account mode and turned off all extensions

went to site, logged in and reset chromo pool, updated, imported chromo data(nothing came in)

imported records(nothing came in) no errors in console

set to scientist and BOOM! it 'worked' started betting, but with no match data to go on so pretty useless.

I suggest you check out [what is going on over here:](https://github.com/mrmoss/saltybet_tools) as far as match data to cull, its all very fresh and doesn't require the user to store and maintain their own records.

anyways... data imports of chromo and records don't work, betting does(on chrome)

nothing works on chromium(prolly a permissions issue since nothing was persisting)

**Comment by calexil** [comment]
in chromium the settings menu says this in console:

Error in response to storage.get: TypeError: Cannot read property 'exhibitions' of undefined

**Comment by calexil** [comment]
full log here: http://dpaste.com/26T0CBW

**Comment by calexil** [comment]
not sure what happened but the records finally imported and this is working on chrome. although I do hope someday you will get it working on chromium since it's probably just some permissions issues.

**Comment by calexil** [comment]
@synkarius Well by cloning the git and packing the extension myself it worked perfectly in chromium after a little tinkering with the records and chromo.

so, we're all good. It's bettin away.

awesome job with this project btw!!
