### ISSUE TITLE
[Suggestion] Mark current betting mode as active

### ISSUE THREAD

**Issue by UnBayleefable** [synkarius/saltbot#115]
changing the button colour of the current active mode to signal that it is currently selected

**Comment by calexil** [comment]
this would be kinda useful, but again ultimately unnecessary as you can simply

press f12 and go to console, go to logs, and tik the 'hide network'

click a mode, voila

**Comment by reconman** [comment]
Fixed in https://github.com/synkarius/saltbot/commit/c40f244753b3db297b1eb54f31bd5e203f652066
