### ISSUE TITLE
[Suggestion] Mode sequence display

### ISSUE THREAD

**Issue by UnBayleefable** [synkarius/saltbot#116]
implementation of a text field that displays the current action being performed by the mode to indicate activity (so the user can tell if the mode has thrown an error or is actually running/waiting for input)

**Comment by calexil** [comment]
@UnBayleefable 

press f12 and go to console, go to logs, and tik the 'hide network'

voila

**Comment by reconman** [comment]
Closed the wrong commit, not fixed yet.

**Comment by calexil** [comment]
is this necessary.. console shows the desired info in the log

**Comment by ACIIL** [comment]
If i knew how to stop past commits from other contributes referencing issues that get pulled in my fork syncs, i really would stop the event. As i see reconmans past issue number triggering notices here every time i do something.

**Comment by reconman** [comment]
If you replace the long commit message of your pull request with a short text instead, you won't reference issues anymore. The referencing only happens because of the pull request description.

**Comment by ACIIL** [comment]
Working on that now.

**Comment by calexil** [comment]
this would also remedy #106 and #156

**Comment by calexil** [comment]
I am not sure is a popup confirmation or a text field would be better

the text field would be less intrusive I suppose

**Comment by calexil** [comment]
is this a won't fix?

I thing the console log should suffice. 

@reconman  time to close?

**Comment by calexil** [comment]
closing because issue seems dead/ not needing a fix
