### ISSUE TITLE
[Suggestion] Clearer user instructions and explaination

### ISSUE THREAD

**Issue by UnBayleefable** [synkarius/saltbot#117]
some space letting the user know about certain things that are necessary but not openly interpreted e.g. 

- letting the user know that the secondary twitch chat opened is necessary for the script to function.

- proper use of the chromosome management - i have absolutely no clue how often im meant to click these buttons right now every time i start the script i reset the pool and then update the genetic weights but im pretty sure that's completely unnecessary. (also maybe a little explanation of what the section is for as im not entirely sure what it does but i know its necessary)

**Comment by UnBayleefable** [comment]
also quick question, if the script encounters a matchup it has no information for but was previously running is it meant to just not bet at all or is it setup to use another method for choosing bets?

**Comment by reconman** [comment]
I would have to take a look at the source code but I definitely know that it will not bet when no information has been recorded about both fighters.

In the case of having records of only one fighter I don't know it by heart.

**Comment by bergerst** [comment]
When there is data about only one fighter then the bot will bet on the one with data if they have won a fight before. The bot will decrease the betting amount by 30 %.

For updating chromosomes: It is best if you just do Reset Pool only every few months. Reset Pool will reset your chromosome to default and you will lose your current chromosome. This is only a good strategy if the algorithm for finding a better chromosome is stuck in a local minimum.

For example when the chromosome leads to heavy upset betting but there would be a better chromosome for betting on the predicted winners instead.

You can update chromosomes anytime and you should let it run for a few dozen generations after about every 500 newly recorded fights. The chromosome will be changed based on the new data combined with the old one.

**Comment by reconman** [comment]
When there is data about only one fighter then the bot will bet on the one with data if they have won a fight before. The bot will decrease the betting amount by 30 %.

For updating chromosomes: It is best if you just do Reset Pool only every few months. Reset Pool will reset your chromosome to default and you will lose your current chromosome. This is only a good strategy if the algorithm for finding a better chromosome is stuck in a local minimum.

For example when the chromosome leads to heavy upset betting but there would be a better chromosome for betting on the predicted winners instead.

You can update chromosomes anytime and you should let it run for a few dozen generations after about every 500 newly recorded fights. The chromosome will be changed based on the new data combined with the old one.

**Comment by calexil** [comment]
This Can Be Closed
