### ISSUE TITLE
Unable to initialize pool: Chromosome is not defined

### ISSUE THREAD

**Issue by Fluffologist** [synkarius/saltbot#118]
I have used this program on my laptop and it worked fairly well with little issue. Now I am putting it on a desktop. So brand new installation with the importing of previous records.

I at first attempted to import the match records. That worked fine.

Next was the Chromosome. After attempting to import, it gave me this error (grabbed via console)

Error in event handler for runtime.onMessage: ReferenceError: Chromosome is not defined
    at ic (chrome-extension://mdbianlngnhelampnobieeoplaadjnpn/records.js:287:23)
    at chrome-extension://mdbianlngnhelampnobieeoplaadjnpn/records.js:329:5

After which I attempted to see If I could just create a new chromosome but it would not let me reset the pool and gave me this error (grabbed by inspecting the salbot ui)

Uncaught ReferenceError: Chromosome is not defined
    at Simulator.initializePool (popup.js:468)
    at HTMLDivElement.<anonymous> (popup.js:529)

So for some reason it struggling with the chromosome. I have no idea and any help would be awesome. Love this project. :)

**Comment by reconman** [comment]
The only way this could happen is if the file strategy.js is not loaded but I have no idea how that could happen. In all cases where records.js or popup.js are loaded, strategy.js with the definition of Chromosome should be loaded too.

Is there any other error message before that?

**Comment by Fluffologist** [comment]
Afterwards I decided to do a clean install of chrome and reinstalled the extension. Before I had tried to uninstall and reinstall the extension but it did not work. So maybe it was something wrong with chrome installation, as odd as that might be.

It is now working properly (for whatever reason).  Thanks for the attempted help though. :)

Everything imported successfully.

**Comment by calexil** [comment]
This Can Be Closed
