### ISSUE TITLE
Character "Team reimisen"causes saltbot to treat it as a team match.

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#119]
During a tournament, " Team reimisen" popped up, it is a regular player and not a team, yet the bot treated the match as a team match.

 Seeing the code why this happens, the bot simple checks for "team",    is there another way to check if a team is a team not by a player's name? This character, as is, cannot be part of the database (or as i understand how it handles match skipping, I never checked the code after).

**Comment by reconman** [comment]
Maybe I can extend the if statement to also check if the current mode is Exhibition mode. Since custom teams only exist in exhibition mode fighters with "Team" in their name can be treated as players in Tournament and Match Making mode.

What Saltbot can't do, however, is betting on single fighters with "Team" in their name during exhibitions.

**Comment by reconman** [comment]
Right now I'm at work so I can't commit the change but if you want you can create a pull request so I only have to merge once I get home.

In line 319 of salty.js the if needs to be changed from

`if (self.currentMatch.names[0].toLowerCase().indexOf("team") > -1 || self.currentMatch.names[1].toLowerCase().indexOf("team") > -1) {`

to

`if ((self.currentMatch.mode == "U" || self.currentMatch.mode == "e") && (.self.currentMatch.names[0].toLowerCase().indexOf("team") > -1 || self.currentMatch.names[1].toLowerCase().indexOf("team") > -1)) {`

**Comment by ACIIL** [comment]
Thanks for looking in.  Well i guess we gotta work with what little data we have for such rare name conflicts.

**Comment by reconman** [comment]
@synkarius Can you please update the chrome extension?

**Comment by synkarius** [comment]
Certainly. It has been updated.
