### ISSUE TITLE
The sorting heiruistic 

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#125]
This issue is in the technical side of how the bot works. 

It tests its data on what matches it knows.  I cannot decide what heuristic methods are better, Should the the bot want most accuracy, or most gains?  

It uses artificial funds right? Not sure how that scales, the current generations sim always increments matches in real time, leading to gains increasing if that match guess was right when tested in the next generation loop, this will drop all other chromes which would be more accurate overall, because one new match gained money. This will make a heuristic based on gains flawed.

So my fork i tried setting it to accuracy, then i did a weighted system combining the two in a ratio, with multiplicity and higher scaling for accuracy.   Results are going about 61-65% acc, this should be good for any test data in the 10ks of rounds, right?   But then, what if winning report only ~60k, what with the same % acc, winnings are ~80k?  (I actually lost this chromosome save....).  What does this mean?

What chromosome weights scale to: accuracy, gains, or both?   
With what i am testing and playing with now, the breakdown weights by tier affect gains most, by fine graining into confidence score about tiers.  Well the other weights affects accuracy most (and this is under the normalized system). I think the chromosome could be broken down into parts, but then what affects what?- i have a guess but that would need its own topic and a report.... 

What do you think of everything above?  Does the heuristic want to be accuracy (for guessing new matches), or best gains (i'm not sure how its internal money system works when applied to real data)?

**Comment by synkarius** [comment]
The heuristic should definitely be gains. At one point we theorized that it might even find its way to becoming an upsets-bot, sacrificing accuracy, if that were the result of gains-focus.

**Comment by ACIIL** [comment]
What do you think of results like this (set to gains)? 

```
A early gens hit:
64.2583% : $25,965,727

But then after a few rounds(20+):
60.8133% : $66,310,002
```

Over time, the % appears to limit towards +60%.  I can guess that the 64%  was from it training into the data like a glove, and the later one, 60.8%, it became more general to handle gains. (Or at worst the 64% was near perfect for handling new matches).

Would it be true if accuracy was at optimal value and we think of all the possible matches, it would max at a percent were it guesses all its matches right, and the remaining percent of all data is the unpredictability of SaltyBet matches?  What would that unpredictability be, maybe ~35-40%?

**Comment by reconman** [comment]
I would say it's 20 - 30 % unpredicability but the saltbot tends to go to around 60 % because betting on upsets pays out more than mostly betting on the non-upset winner. That is why it learns to bet on potential losers.

I just looked up the logic for simulating wins and losses and found a few potential issues with the current code:

- The betting levels influence the simulator behaviour greatly. If you win big with the first few bets then you can potentially earn more money with later bets.
- Payout is calculated with recorded odds. That way some crazy historical one-time odds can mess up the simulation results

Solution for problem 1:
Either the order of matches needs to be randomized which would create random fluctuations in the simulation results or the betting level needs to be the same for all matches.

The second solution creates the problem that it would favour bets with high risk but great reward and ignore the many losses because it would just get back to bailout immediately. If just the sum of money won and lost was taken as the value of a chromosome then it would be heavily influenced by crazy historical odds again. Things like odds of 1:500 where an upset happened.

Discussion of problem 2:
You could instead use some sort of predicted odds for the match instead of the historical ones but I think according to the logs the predicted odds are way off most of the time. I don't have any idea for a solution.

**Comment by ACIIL** [comment]
recorded odds weight? You might like what i'm doing to to the weights at the moment. Observed timeAveWin & timeAveLose, compare them to the old time weight system, compared them to other weights.

This links to my issue #126 request to purge bad times in the database.  Time weight was flawed and it tended to be high, so i split it into average win and lose times. I think something happened:


```
chromosome:
oddsWeight : 0.0015053873772109302
timeAveWin : 0.15785235258799132
timeAveLose : 0.015269576061789
winPercentageWeight : 0.0145404455439018
crowdFavorWeight : 0.021456246919048797
illumFavorWeight : 0.02749833787113178
wX : 0.018233690193885446
wS : 0.028108542310932263
wA : 0.02561968596139801
wB : 0.003524609875857996
wP : 0.012675991669992254
wU : 0.05023438545792577
lX : 0.0010104048001627639
lS : 0.05170176592828432
lA : 0.0006117872690396243
lB : 0.051971993732460635
lP : 0.01130868169133773
lU : 0.03463733416766512
oX : 0.0016983778399997753
oS : 0.010584533703294057
oA : 0.10045730210314295
oB : 0.0006740181070809994
oP : 0.0016901035882891284
oU : 0.003611012899634864
wtX : 0.020398939870823127
wtS : 0.0023267391159967907
wtA : 0.018659596890023618
wtB : 0.08612033158051617
wtP : 0.0026348532504849795
wtU : 0.020429170219169967
ltX : 0.003324405940748538
ltS : 0.06837298771283473
ltA : 0.04470672446857958
ltB : 0.026937953976843076
ltP : 0.041835506725975045
ltU : 0.0177762225865472
rank : 1 -> 60.7759%,  $66,582,002
```

Before time weight forced a 50/50% to win and low average. You can see how different they are now.

I think, as matches continue and everything evens out, oddsWeight  is bad, winPercentageWeight depends more of tier weights for win/lose counts summary.  That timeAveWin is extremely important over else. But, this is the current dominating strategy in this system so don't take my word for it.

The new time weights tells such that characters that win fast will tell more than wins, that losing slowest kinda muddles its weight with everything else.   You can see new patterns, such that the favor odds are worth more than  timeAveLose,  actually i think there is a new error here related to my normalization, or how favor scaling is used....  oh' boy something new to debug.

**Comment by reconman** [comment]
I mean recorded odds, not recorded odds weight. If the odds for a match were 1:100 and it was an upset then the chromosome would be optimized to bet in such a way that it would win.

**Comment by ACIIL** [comment]
With the new time purged data and sorting for acc in my fork i hit over 67%! I never get over 65 beyond first gen data.

```

chromosome:
oddsWeight : 0.04459522299006137
timeAveWin : 0.02213588810954802
timeAveLose : 0.022952398404378266
winPercentageWeight : 0.033676386243398505
crowdFavorWeight : 0.057054205752362315
illumFavorWeight : 0.0016509516110087808
wX : 0.0007104143058675698
wS : 0.03223441120893254
wA : 0.0018753575864967884
wB : 0.001602213370671085
wP : 0.048012839832516516
wU : 0.025675343692862864
lX : 0.04459522299006137
lS : 0.0401680772402864
lA : 0.024256754722205752
lB : 0.03879169762299998
lP : 0.0013286842575837275
lU : 0.04961189288685833
oX : 0.00213181277083892
oS : 0.06846301876102519
oA : 0.02594013062389737
oB : 0.0011135702292551172
oP : 0.0014887168846758727
oU : 0.02662051505345899
wtX : 0.051983975170551734
wtS : 0.0018753575864967884
wtA : 0.020853045867275908
wtB : 0.029226873552645805
wtP : 0.0313659985676607
wtU : 0.06776722378942693
ltX : 0.030762244075271672
ltS : 0.05340265346249365
ltA : 0.02213588810954802
ltB : 0.02185359981606181
ltP : 0.05088707415434695
ltU : 0.0012003386969684923 -> 67.1114%,  $40,990,510

```

Another little interesting detail, when heuristic is for best money gains, timeAveLose tends to dominate everything as a base higher, and also does so in repeated pool restarts, something here is telling.

**Comment by ACIIL** [comment]
New notes that may help understand what i'm doing.
Using the built-in tool for checking upset gains.  From Reading this story on the bot:
http://explosionduck.com/wp/story-of-a-betting-bot/

I got this with my current runs:

```
Simulator.prototype.evalMutations("mass");
undefined
popup.js:369 avg denom: 7, avg upset: 3, avg nonupset: 8, 
upsets called correctly: 36.75%, (8464/23034), 
nonupsets called correctly: 72.67%, (45834/63074), 
minimized losses: 25.96%, (22362/86134), avg loss minimization amount: 60.39%
popup.js:447 

--------------- matches processed: 86134
popup.js:453 cs: 63.05872245570855%, $NaN
popup.js:455 average IPU money: NaN
```

Does this look reasonable?   I do not know. I do see some problems, 
see the none upsets called correctly: 72.67%,    That % is way higher than what a average generation top % per generation says!   Clearly i'm not understanding something all the data is giving here.

The line,  The avg denom: 7, avg upset: 3, avg nonupset: 8.  -- I think these are odds but i do not know what denom & nonupset mean,  it got me thinking.  They are averages?   I wonder what "ave upset" would look like on a histogram of odds based on upsets.... I might be able to graph this, it might look shrewd, which would make upset bets flawed.

Anyways, i think i'm going see how the deeper system calls handling things before sorting the best chromosomes , i sense something is off.  The new mutations branch will affect this now.

**Comment by calexil** [comment]
I am testing your chromosome with the cleaned data at a 2.2 multiplier for a bit, im rank 505 now Ill see where it gets to tomorrow evening

**Comment by calexil** [comment]
I am hesitant to move my multiplier cause I want steady growth and it seems like everytime I climb it past 2.2-2.1 it starts loosing a ton, and I just stagnate

**Comment by ACIIL** [comment]
See my #135 reply. All my work on my fork cannot be ported without understanding the changes.

**Comment by ACIIL** [comment]
So back the issue. My me understanding the code. What you see as top of every chromosome is % of all the matches it tested guessed right, followed by money gained by how well it scaled confidence. 

Confidence is by comparing the total score between characters, the highest character of the total is selected.

The default training is for money.  So it will scale confidence in ways to minimizes losses on bad predictions or scale high for other patterns of gains.   This does not mean it will select the right character correctly. 

Training for better accuracy means the bot will pick the correct character based on the pattern of stats, it does not learn to scale confidence for money.

So chromosome -> character scoring -> summing scores -> picked character is highest score of the two and prediction is (character score)/total -> prediction affect amount bet.

In Heuristic terms, scaling for money is more granular than accuracy, it helps the training better. 
But we still need accuracy, as issue #133 covered.  If you want the bot to pick correctly more, to be right within limited resources, the heuristic needs to preserve some level of accuracy. And that accuracy has a probable high limit, where the randomness of AI, error in implementation, etc, prevents accuracy being  100%.  

So i say a heuristic needs both accuracy and money, but it must allow exploration, it must scale between the magnitude between a percent value and millions in salt.      I think i got something going on my fork. ready for testing on that master.
