### ISSUE TITLE
prediction printout errors? (Crow favor errors)

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#127]
There may be silent errors in the prediction printout. The favor messages are silent.

See in strategy.js, around lines:
```
var line3 = "\xBB ";
if (crwdMessage) line3 += crwdMessage;
if (ilumMessage) line3 += "  ::  " + ilumMessage;
if (line3.length > 2) console.log(line3);
```

From what data these are given  in debug mod, should line3 be filled? Should it be printing crowd/illuminati favor and its scales?

**Comment by reconman** [comment]
The if (debug) needs to be removed in order for this to be printed.

**Comment by ACIIL** [comment]
Doing a check on c(n)Stats.cfPercent and c(n)Stats.ifPercent, in
`ConfidenceScore.prototype.execute = function (info) `
These appear to be null as they entire the scoring.

The favor algorithms appears to be broken at the input source. Which means the chromosome simulation is using useless data as part of the scoring system. And it means these crowd favor weights are random and unused. 

I hope this does not mean favor scoring was always broken.

**Comment by ACIIL** [comment]
update:
Crowd favor & Illuminati favor matches are filled at startup with calls in records.js   There is something interesting:

This function populates match stats that are used for prediction
`updateCharactersFromMatch()`

Here in its lines for favor:
```
// expert favor is seemingly worthless but what the hell
	if (mObj.if != null && mObj.if.length > 0) {
		if (mObj.cf == 0) {
			c1Obj.crowdFavor.push(1);
			c2Obj.crowdFavor.push(0);
		} else if (mObj.cf == 1) {
			c1Obj.crowdFavor.push(0);
			c2Obj.crowdFavor.push(1);
		}
		if (mObj.if == 0) {
			c1Obj.illumFavor.push(1);
			c2Obj.illumFavor.push(0);
		} else if (mObj.if == 1) {
			c1Obj.illumFavor.push(0);
			c2Obj.illumFavor.push(1);
		}
	}

```

Few observations. 
1)  The ".if",    this _should_ (hopefully) not be a case for conflicting name space, as the intent is "Illuminati favor". I got lost  as i was searching what a .if statement was (its not a statement), also my text editor (notepad++) was colorizing ".if" like a function, how horrifying.  Here ".if" is used for item references many times in the script.     Better to just rename ".if" something more clearer.
2) Here ".cf" (crowd favor) depends if Illuminati favor exists, these should be treated as independent cases. Just as they are used in prediction as independent cases.
3) Some good new for back porting possible fixes,  all this characters Obj filling  happens at startup, so if the records holds favor data it can still be used.

I am still finding out why favor data is not being filled for the prediction scoring.

**Comment by ACIIL** [comment]
I'm pinning the problem on 
` if (mObj.if != null && mObj.if.length > 0) `

 "mObj.if" at debug is a value,   "mObj.if.length" at debug is undefined.

I think it meant:
`(mObj.if != null || mObj.cf != null ) `


....

Got it all to work again.   There was a few other errors related to what was referenced in users favor code that also needed to change.   A lot of it would show using the chrome debugger and inspecting the values. 

I guess my question is now, was crowd and Illuminati favor always broken?

**Comment by reconman** [comment]
I fixed the problem in https://github.com/synkarius/saltbot/commit/6c297849940f979ec946ea83916446badfc34ef0 but I've just encountered a match where I had no info about one character but it still said that the character has a higher crowd favor so some bug is still hidden.
