### ISSUE TITLE
Official Saltbot Subreddit

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#138]
I decided to create a development and discussion subreddit for the bot in cases where discussion on reddit would be more convenient it can be found here:

https://www.reddit.com/r/saltbot/

please pm me for an invite.
https://www.reddit.com/message/compose/?to=calexil

@synkarius
@ACIIL
@Ampheric
@AoiHaru
@CritikalFreeze
@db-kai
@dirtyjobs
@ehissey
@HotPotSoup
@Jrad7
@KingMikeGames
@kurzimov
@OldDragon2A
@reconman
@retsu3
@Yousef-
@zgf2022
@Zyrixion
@bannable

**Comment by reconman** [comment]
Thanks for your effort @calexil . Maybe we can discuss the changes for mutations there instead of here since I'm getting tons of emails from github. I think I got around 100 mails in the last few days.

**Comment by ACIIL** [comment]
Sorry.  I'll keep Mutation comments out of these issue pages. I'm starting to run out of things to tinker actually.


Actually, I never use reddit. ever.

**Comment by calexil** [comment]
yeah that was the idea

**Comment by calexil** [comment]
@ACIIL if you need an invite message me https://www.reddit.com/message/compose/?to=calexil

**Comment by synkarius** [comment]
This is a good idea. I've linked to the subreddit from the guide.
