### ISSUE TITLE
simulated money gains appears biased.

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#142]
I was studying how the money gains in the sim work.   I am kinda lost.

It began when i saw this line 
```

if (betAmount > 20000)
	betAmount = 20000;

```
I thought, well ok its just capping... but then why!  I asked myself,  would preserving some aspect of the rolling magnitude be better?  This "magnitude" being how effective the sim is for gaining money using confidence each match.  

I looked and found the confidence values used in a strict formula (sorta like this)
`current * 0.1 * confidence`
So the simulated gains would only up 1.1 for each game it predicts right & max confidence (and when not applying that matches odds to the money). That extra odds being applied on the confidence is another part of the bias.

So then i looked at how all the matches are run through....
And here is the bias problem, the matches have no order! They are dependent on how its was stored and recalled in memory. The order of matches are effectively random and they also determine the running total, this is not good for the final money prediction, the order of matches (and whats predicted wrong or right) will affect the outcome, and they should not, as changes to the stored matches affects the gains; Its like the butterfly effect.

So now i am thinking of way to remove the bias:
1) Split matches and ordered for predicted right, then wrong; run gains first, then loses.   This will remove some bad eggs in the loses that would cripple the money early, for example.

2) Convert the running total money into adding confidences for wins, then subtracting confidences for loses.

3) Rethink if using the odds in the sim for the above two would even matter given how it will affect how effective confidences are measured. 

Ether way, the code block that will change will not be easy to do, a lot of other parts of the system ties in the prediction and money sim code.

I need some help here.

**Comment by reconman** [comment]
I will have to look through the whole simulation code myself once I get back from Venice on Saturday. Right now I don't have internet in my hotel room but only in the lobby when I get back from work.

**Comment by calexil** [comment]
poke

**Comment by calexil** [comment]
@ACIIL were any of your issues resolved in the mutation branch?

if so.. they can probably be closed

**Comment by ACIIL** [comment]
nope.

**Comment by ACIIL** [comment]
Just had a thought how to explain the issue better. 

I believe if the records history was scrambled out of order, the result is that the percent correct will be the same and the total gain will be different.  As the gain is different, the system is not a good predictor for how well it makes salt on the records and thus live data.

**Comment by synkarius** [comment]
That's a very good explanation. What if we randomized the order of the data in memory before each generation?

**Comment by ACIIL** [comment]
I believe the gain will still be as chaotic as random order of major upset matches. I was thinking shifting the gain heuristic to formulas like performance of "minimized losses" and more recently "missed gains" (in the test branch) better reflects how well the chromosomes plays wisely with salt. The problem is these functions are in a independent system from the best chromosome sorting methods currently.

**Comment by reconman** [comment]
I'm currently working on Saltbot again and I've got an idea for this issue: What if the bot always starts with say 10,000 $ in each round. This way the order of the recorded bets does not matter anymore.

Only a few lines of code need to be changed in order to do this.

**Comment by Zyrixion** [comment]
Since we're on the topic, I sometimes feel like the influence of improbable dream upsets on how much money the bot theoretically made for the purposes of chromosome generation might actually be purely detrimental to the process as a whole, since it can end up selecting for traits that are detrimental to accuracy for regular matches, but in one case caused a prediction on an upset worth a disproportionately massive amount of salt.  Also, limiting the influence of matches with massive odds might give a more realistic picture of the estimated profits based on average performance on average matches.

**Comment by ACIIL** [comment]
@reconman yeah using a $10k base is pretty much like just using the raw confidence float and adding it up to something useful as a heuristic.  But now that "$10k" is just 10000x to the confidence score. lol

@Zyrixion, i was testing a balance between high money gains to mostly being correct (back in may?).  Yeah right now the situation of extremely high upsets (combined with the match samples test order) can sway into bad training, which was why the test branch can be tweaked to test ratio balances of gains ($) to of accuracy (%). But then made me realize how the confidence value for each match being upset or not is more direct and better for not being affected by $ or % when combined to tracking if the match was a upset or not & how confident guess was true. Also the system of measuring upsets is a simple logic compare of  current match odds, to what side won, and not what the bot voted.

**Comment by reconman** [comment]
I've already removed most of the bias in the typescript migration.  I've implemented it like I commented above with using 10k starting money every round, so early matches don't have any influence on later matches.
