### ISSUE TITLE
floating point errors

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#146]
JavaScript treats all numbers as floats, not ints.  There a numerous situations where floats are being compared for equality or depends on being exact to something; Like the equal chromosome function, or something like errors code checks:
```
for (var i = 0; i < cObj.odds.length; i++) {
		if (cObj.odds[i] != -1) {
			oddsSum += cObj.odds[i] * chromosome["o" + cObj.tiers[i]];
			oddsCount += 1;
		}
	}
```
Here it would be safer to check `(cObj.odds[i] < 0) `.

Rounding errors can come from anywhere, especially if the the sources are from tallying numbers.   I'll see what i can do to improve float usage.

**Comment by reconman** [comment]
Look at my example, number equality works in JavaScript.
https://jsfiddle.net/Lpo9ez38/

This code works because if the odds of a character are unset, they are set to -1. This is done in records.js, line 131 and 132.

**Comment by ACIIL** [comment]
I was thinking if it is generated to be a value at startup then its ok. And the solution is trivial.

But really the case is with rolling edits to floats, in what case Murphy's law will happen with trying to equal two floats which had a floating point error.  

Back then i was seeing the chromosome equals func, then i seen its used for initial population generation and preventing duplicates (it won't),  i was worried if someone else would pick up the code later and need to fixing the equals functions then. 

I say this issue is for best practices with dealing with floats that are going to be floats, and not floats that are going to be treated as ints (By being constants like -1).
