### ISSUE TITLE
add/edit global settings/options.

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#147]
I am ready to add new settings to the code. Where are global settings held and how do you access them?

From what i seen right now, looks like `var Settings = function () {` in `salty.js`  is what i am looking for.  I see a pointer `ctrl` that seems to refer to it across two files. Perhaps this is how i would access the settings properly?

**Comment by ACIIL** [comment]
I wish saltBot implemented options in this way:
https://developer.chrome.com/extensions/optionsV2

It would make life much easier. I do not want to attempt this on my own as doing so would fragment the codebase.

**Comment by reconman** [comment]
Sorry for the late answer, for some unknown reason my phone did not show any notifications for mails for a week.

Extendending the options is rather difficult.

First the Settings assignment you found needs to be extended by the additional property you want to use.

Then either the popup.html or config.html page needs to be edited. Add your input elements necessary for specifying option values there.

Next edit the popup.js or config.js file to add change handlers to the input elements similarly to the existing elements. You also need to add the loading of saved config settings there.

```
chrome.storage.local.get(["settings_v1"], function (results) {
	$("#te").prop('checked', results.settings_v1.exhibitions);
	$("#ait").prop('checked', results.settings_v1.allInTourney);
	$("#ctl").prop('checked', results.settings_v1.tourneyLimit_enabled);
	$("#tourney-limit")[0].value = results.settings_v1.tourneyLimit;
	$("#toggleKeepAlive").prop('checked', results.settings_v1.keepAlive)
});

$("#bdr")[0].addEventListener("click", drClick);
$("#te")[0].addEventListener("change", teChange);
```

The click and change handlers for most input elements call the function btnClicked defined at the top which sends a message to the records.js script.

The records.js script receives the message in line 317 and calls the corresponding method of the Controller class in salty.js (e.g. setExhibitions in line 395 of salty.js) which sets the setting in the chrome local storage.

**Comment by ACIIL** [comment]
Yesh, My head is spinning. Thanks for the tips though, i'll have to keep looking at this to help understand the complexity.

**Comment by reconman** [comment]
Using the options_ui only works for the second part of the config which appears when you click on the cog wheel icon.

Other than being a native version of a config page it does not improve managing the config options. You still need the code posted above with chrome.storage.local.get to load config values into the HTML elements and use click/change handlers.

The logic of the config pages sending messages to the records.js script which calls the salty.js script could be refactored, I think.

**Comment by reconman** [comment]
Won't fix, there's no benefit.
