### ISSUE TITLE
Consolidate twitch chat record keeping to a single tab

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#155]
the twitch chat on saltybet.com should suffice, can someone explain to me why a separate tab is needed?

**Comment by reconman** [comment]
It's because the twitch chat is embedded into saltybet.com. Javascript on saltybet.com cannot access the DOM of twitch.tv because of the same origin policy.

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by calexil** [comment]
ah
