### ISSUE TITLE
Add indicator to show that records and chromo are successfully imported

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#156]
just a little popup to confirm the data was imported would be nice

the popup still crashes on import

#106

**Comment by calexil** [comment]
@mrmoss any idea how to do this?

**Comment by reconman** [comment]
Fixed with https://github.com/synkarius/saltbot/commit/4ff4aab66f2ee4dc5def03a43450fd625a8ead1b

**Comment by calexil** [comment]
awesome work!!
