### ISSUE TITLE
Chrome/Chromium Memory Maxing

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#164]
the bot extension seems to be completely maxxing out whatever system it is on..

memory is not being released correctly.

video toggle did not help

tested on 4gb, 8gb, and 16gb systems... same result

this thing shouldn't need 4gb to run, something is wrong

**Comment by ACIIL** [comment]
I Cannot help with this. Not enough info.

**Comment by calexil** [comment]
for starters you could check your memory usage in chrome/chromium

and give me a number

**Comment by calexil** [comment]
Ill reopen this after more research into why this thing is using 4gb of memory...

**Comment by Zyrixion** [comment]
Can confirm, it's leaking memory somewhere.  My chrome instance running it continues to grow in memory usage until it inevitably crashes.
