### ISSUE TITLE
Convert records into .csv for faster indexing and edit-ability.

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#165]
@reconman would it be too complicated to switch the records from txt to csv?

This could theoretically speed up the bots ability to lookup records by giving better parameters for the lookup

The list could be abc order, with the parameters split into collums.

ie: X coordinate.... Y coordinate 

raw text is extremely slow to load and sort, we need to fix this before #164 and #158 

[Example](https://u.teknik.io/7sc9u.csv)

**Comment by reconman** [comment]
Ummm, the match list is already in CSV format, just without headers and sorted by date. It just doesn't download the file with the file extension .csv.

**Comment by calexil** [comment]
lol k
