### ISSUE TITLE
Fix 'Complex Method' issues in Saltbot .js through refactor

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#170]
[CodeFactor](https://www.codefactor.io/repository/github/synkarius/saltbot) found an issue: Complex Method

It's currently on:
[src\salty.js:95-142
](https://www.codefactor.io/repository/github/synkarius/saltbot/source/master/src/salty.js#L95)Commit 5b4d14c541fe999a1c23104fb1c046630faf6a37

[**All complexity issues here**](https://www.codefactor.io/repository/github/synkarius/saltbot/issues/master?category=Complexity)

**Comment by ACIIL** [comment]
I know what it is referring too!  That area with how it does  `var self = this;` and uses `self ` was my my first big "nope" thinking i could touch globe settings and understand what i am doing.

Well there is nothing broken to fix, the code handling settings i feel is chaotic to use and possibly the single greatest refactor saltbox would benefit from.

**Comment by calexil** [comment]
check out the ignored issues on codefactor.io

https://www.codefactor.io/repository/github/synkarius/saltbot/ignoredissues

**Comment by reconman** [comment]
Who ignored them? I didn't.

**Comment by calexil** [comment]
I did, a lot were css related.. mostly finicky things related to semantics... not function

**Comment by calexil** [comment]
@reconman I am working on a travis ci setup to check the extension currently.

Ill move on to the refactor when I get braver

**Comment by reconman** [comment]
A Travis CI does not really help when the extension depends on chrome functions and on saltybet.com. How would you run unit tests?

Also why is your Github account rapidly opening issues for CodeFactor issues?

**Comment by calexil** [comment]
I was testing something.. I'll stop.

you can setup selinum to check the js for stability from what I've read

also that the extension installs and runs without errors

**Comment by calexil** [comment]
https://github.com/apiaryio/chrome-extension-ci

**Comment by reconman** [comment]
I have experience with Selenium but you cannot do anything like clicking on the Saltbot icon in the toolbar. Also you can only record commands in Firefox.

**Comment by calexil** [comment]
dang
okay ima rip out travis, and look for a js scanner

codefactor.io kinda does it, but I bet theres a better tool

**Comment by calexil** [comment]
closing due to rebase
