### ISSUE TITLE
Fix 'Unnecessary escape character: \-.' issue in src\lib\date.js

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#186]
[CodeFactor](https://www.codefactor.io/repository/github/synkarius/saltbot) found an issue: Unnecessary escape character: \-.

It's currently on:
[src\lib\date.js:58
](https://www.codefactor.io/repository/github/synkarius/saltbot/source/master/src/lib/date.js#L58)Commit 5b4d14c541fe999a1c23104fb1c046630faf6a37

**Comment by calexil** [comment]
there are many of these

**Comment by reconman** [comment]
You don't need to create one Github issue for all CodeFactor issues. One is enough.

Also \lib\ indicates that it's an external library so there is no point in editing the code.
