### ISSUE TITLE
Cannot Update Genetic Weights

### ISSUE THREAD

**Issue by gordon1470** [synkarius/saltbot#187]
When I click the Update button the console spits out this error message and doesn't do anything else. This is on the latest commit.
`Error in response to storage.get: TypeError: Cannot read property 'mate' of undefined
    at Object.callback (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:444:21)
    at Simulator.evalMutations (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:194:23)
    at HTMLDivElement.<anonymous> (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:551:13)`

**Comment by reconman** [comment]
Have you just started using Saltbot? If so have you imported a chromosome or clicked on reset pool?

**Comment by gordon1470** [comment]
No, I've been using it for quite a while. I imported the chromosome from the sample data. When I reset the pool and try to update the weights again, the UI locks up completely until I disable and reenable the extension and refresh the page or restart chrome. I tried reimporting the chromosome and tried again, and the UI locked up again. This appears to be a new development. No errors are put out to the console, and the bot will still bet normally.

**Comment by gordon1470** [comment]
I tried again with a fresh clone of the latest commit and this is what prints to the console when i run "Update Genetic Weights" with my data. 
```
-
chromosome:
oddsWeight : 3.6697843393798886
timeWeight : 0.5
winPercentageWeight : 1
crowdFavorWeight : 0.7055170755165155
illumFavorWeight : 1
wX : 0.2073454800703492
wS : 12.0906082630695
wA : 7.509018601967533
wB : 1.3070840137459832
wP : 0.6507257357558891
wU : 0.5
lX : 1
lS : 1.8471130467188797
lA : 0.25648601999325044
lB : 4
lP : 5
lU : 0.5
oX : 1.296325629711329
oS : 4
oA : 3
oB : 0.18605869138487827
oP : 0.5809957705026872
oU : 0.18239716031947562
wtX : 14.435761524405065
wtS : 4
wtA : 3
wtB : 1.2125468398767496
wtP : 1
wtU : 0.03886080694667771
ltX : 0.15710560052235914
ltS : 2
ltA : 3
ltB : 4
ltP : 3.28728897701122
ltU : 0.5
rank : 1 -> 65.8918%,  $31,852,659
popup.html:1 Error in response to storage.get: TypeError: Cannot read property 'mate' of undefined
    at Object.callback (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:444:21)
    at Simulator.evalMutations (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:194:23)
    at HTMLDivElement.<anonymous> (chrome-extension://kohegpahifbppmcpmepdhjcehegmdomd/popup.js:551:13)
```

**Comment by reconman** [comment]
The locking up is because of a change in how the chromosome is calculated. It just takes much longer until a generation is calculated. Calculating one generation takes about 1 minute now. 

You don't need to deactivate the extension.

**Comment by ACIIL** [comment]
This looks like the main branch. This chromosome type won't work with the new mutation branch. I don't understand how the main branch will start to have problems with its original type of chromosome.

**Comment by reconman** [comment]
@ACIIL I can import and mutate chromosomes just fine.

**Comment by ACIIL** [comment]
@reconman you implying main branch to main branch chromes?  If you were inter swapping branch and chromes, i guess the behavior becomes undefined, errors would pop up trying to access the "time" entries.      Given what you say, this is not a issue.

How curious, i want to study what changed!

**Comment by calexil** [comment]
this is no longer an issue
