### ISSUE TITLE
Fights not being recorded correctly on txt file

### ISSUE THREAD

**Issue by DrOutside** [synkarius/saltbot#190]
Fights other than the ones imported show up as this on the txt file when exported: https://i.imgur.com/ue0JczT.png

Is this normal or would this cause issues?

**Comment by calexil** [comment]
looks right to me

**Comment by calexil** [comment]
this is resolved with indexedDB

**Comment by reconman** [comment]
Not resolved via IndexedDB, I found it by accident.

Matches are writting using only LF (\n) at the end of the line to go to the next line. Notepad can only handle CR LF (\r\n).

Open the file using an editor like Notepad++ to see the line breaks.
