### ISSUE TITLE
Bot is not collecting fight data...at all...

### ISSUE THREAD

**Issue by Hammeredmantis** [synkarius/saltbot#193]
Not sure what is going on, or why but I have let it run 24/7 for about a week now, and it has collected absolutely zero data on fights as they happen which is making for some interesting salt losses (come home after a full shift to find I have lost over 50% of what I had even though it is making bets of 1k or less)

**Comment by calexil** [comment]
CONFIRMED

still happening in 2.5

@reconman  eek, this is bad

**Comment by calexil** [comment]
![screenshot at 2018-03-25 17-41-32](https://user-images.githubusercontent.com/3487071/37880288-d78b9922-3053-11e8-9b25-989fc43a0fd7.png)

**Comment by calexil** [comment]
data is being collected, just not displayed in the database page
