### ISSUE TITLE
Match data not being culled from indexDB properly

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#194]
![screenshot at 2018-03-25 17-24-59](https://user-images.githubusercontent.com/3487071/37880298-ef873180-3053-11e8-9793-535749e2f2c2.png)

**Comment by reconman** [comment]
It's not that bad of a bug, the match data is not shown but when you click on Export in Record management, the data is downloaded as normal.

**Comment by calexil** [comment]
it is not for me, and the bot refuses to bet. 

probably related #193

**Comment by reconman** [comment]
Nah, it's because IndexedDB stores data for domains instead of extensions. The page with the match data is on chrome:extensions://.... but the match data is currently stored on saltybet.com.

I just have to find a way to transfer the IndexedDB operations to the twitch_background.js file.

**Comment by calexil** [comment]
ah

**Comment by reconman** [comment]
I'll fix it tomorrow, it's 1:30 AM for me and I have to wake up at 6:45 again.

**Comment by calexil** [comment]
sounds good, sleep well

**Comment by reconman** [comment]
The bot should work fine except for the matchdata page. Can you calculate chromosomes and set the bot to Scientist mode?

**Comment by calexil** [comment]
thought you were going to bed lol, yes it imports the chromo fine, and I can set it to scientist mode. but it wont bet. it just sits there

**Comment by reconman** [comment]
Should work now.

@calexil Make sure to reimport the match data and **definitely** recalculate the chromosome. You can't use the old chromosome with this version.

**Comment by calexil** [comment]
fixed

**Comment by calexil** [comment]
recalc was REQUIRED
