### ISSUE TITLE
Fix 'Expected a 'for-of' loop instead of a 'for' loop with this simple iteration' issue in src\strategy.ts

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#196]
[CodeFactor](https://www.codefactor.io/repository/github/synkarius/saltbot/overview/master) found an issue: Expected a 'for-of' loop instead of a 'for' loop with this simple iteration

It's currently on:
[src\strategy.ts:457
](https://www.codefactor.io/repository/github/synkarius/saltbot/source/master/src/strategy.ts#L457)Commit 0e95b6c4f54b6d1c54da79ce81ee18df6cfbe7b6

There was a lot of these too, but I'm pretty sure its just tslint semantics crap that doesnt affect performance

**Comment by calexil** [comment]
let me know if we can ignore them, I have fixed all the != >> !== and == >> === items.

@reconman

**Comment by reconman** [comment]
Please wait before you do any further fixes. I'm fighting with merge conflicts now because I've already fixed many on my side.

**Comment by calexil** [comment]
oh sorry I didn't know you were working on it too.

**Comment by calexil** [comment]
ill stop doing things

**Comment by reconman** [comment]
I'm done with my push.

**Comment by reconman** [comment]
The only thing you gain by replacing the existing loops with a for...of loop is that you don't need to initialize index variables.

I've already replaced many loops with for...of, which lead to some unexpected bugs.

Here is the TSLint page for that rule https://palantir.github.io/tslint/rules/prefer-for-of/ with the mindset behind it.

On https://palantir.github.io/tslint/rules/ all rules of TSLint are listed.

**Comment by calexil** [comment]
issue: Expected a 'for-of' loop instead of a 'for' loop with this simple iteration

is going to be a rather large undertaking, and as you stated, probably useless, I am going to ignore them

**Comment by calexil** [comment]
I am fixing things I can fix from here: https://www.codefactor.io/repository/github/synkarius/saltbot/issues

let me know what else can be ignored

**Comment by calexil** [comment]
are you fixing things rn?

**Comment by calexil** [comment]
if so I'll let you go

**Comment by reconman** [comment]
@calexil I've just pushed some fixes for TSLint issues, but that's enough for today.

"Wrong object key literal order" is useless because it's only for readability. The other stuff can be fixed.

**Comment by calexil** [comment]
otherwise we'll be steppin on each others feet(code)

**Comment by calexil** [comment]
okay I'll get on it, I think the complexity issues can be ignored as well

**Comment by calexil** [comment]
its all just semantics and legibility, nothing performance related

**Comment by reconman** [comment]
After the current version of Saltbot is bug-tested, the next step will be converting Javascript classes into Typescript classes.

That way the compiler knows the parameter types of any methods and bugs can be found.

**Comment by calexil** [comment]
not sure how to fix em tho

**Comment by reconman** [comment]
Those can be fixed by adding 10 as second parameter. Like this:

```
let a = "10";
parseInt(a, 10);
```

But you can also convert strings to numbers using the unary + operator like this:

```
let a = "10";
let parsed = +a;
```

**Comment by reconman** [comment]
@calexil You've broken the tslint.json file with cc897c57874c5df42b1adb93768e8d19611a77d8.

I've pushed a fix for that.
