### ISSUE TITLE
Update Genetic Weights appears broken

### ISSUE THREAD

**Issue by MichaelHumphrey7** [synkarius/saltbot#200]
As of yesterday night (3/27/2018) updating genetic weights would set every genetic weight to a very small number (from ~10^0 -> ~10^-3) in one or two generations.

**Comment by reconman** [comment]
That in itself is not a problem. The weights may be extremely small, but the bot doesn't really have normalization.

Some time ago some code changes were made, which lead to such small weights. I've tried to introduce normalization to make the values more human-readable, but they were rejected by another developer, who removed it again.

I'll try adding normalization again, but it may break stuff, so I have to be careful.
