### ISSUE TITLE
Tournament betting not going all in despite option checked

### ISSUE THREAD

**Issue by veritablyclean** [synkarius/saltbot#208]
Let me know if there are any log files needed

**Comment by reconman** [comment]
What version of saltbot are you using? Chrome store? Self-built?

If self-built, how old are your sources?

I'm asking because 5 days ago I introduced faulty code which made the bot not detect tournament anymore. I've since fixed it.

**Comment by ihawk007** [comment]
I have the same problem.  Using version 2.5.1 downloaded through the Chrome store.  Imported match records and chromosome from 3/25/18.  I recently reinstalled Chrome.  I've tried removing the extension and installing it both through the Chrome store and from the github separately.

**Comment by reconman** [comment]
I think it's a timing problem, the bot is betting fine on my side.

I've just pushed a new commit so Saltbot only starts acting when the box to put your bet in appears. At that moment the (Tournament balance) element should also be visible, which indicates tournament mode.

**Comment by reconman** [comment]
During the final match, the text (Tournament Balance) is not shown. The bot only bet 80 $.

**Comment by calexil** [comment]
can anyone confirm 01c3560 fixes this?

**Comment by reconman** [comment]
If the bug still happens, please attach a screen shot of saltybet after the bot has bet and some of the last console messages.

**Comment by ihawk007** [comment]
Disabled Salty Finder and it worked like normal.  Salty Finder must remove the (Tournament Balance) which causes the bot to not think its a tournament.

**Comment by reconman** [comment]
Yeah, it's this line right here:
https://github.com/mrmoss/saltybet_tools_chrome_extension/blob/e89753a6781147a9aa03c5ca56efcbb95f297bf7/js/background.js#L63

**Comment by calexil** [comment]
https://github.com/mrmoss/saltybet_tools_chrome_extension/issues/10


issue opened

**Comment by calexil** [comment]
https://github.com/mrmoss/saltybet_tools_chrome_extension/commit/acf6d09c13d8e0257e12e82091469511af98fb5c


should resolve this
