### ISSUE TITLE
Match data stopped recording

### ISSUE THREAD

**Issue by nixpayn** [synkarius/saltbot#209]
I happened to look at my match data today, was trying to figure out why ive been losing so much lately (literally freefalling for days) and i noticed match data stopped recording on 15-04-2018 @ 191,998 entries.

I know that has nothing to do with loses but still. Its been running non-stop for over a month now so seems kinda random to just stop recording.

![image](https://user-images.githubusercontent.com/38497537/38931902-a986f0b6-42e2-11e8-8813-aa8be7e89938.png)

**Comment by calexil** [comment]
can anyone else confirm @reconman @ACIIL @HotPotSoup

**Comment by nixpayn** [comment]
It looks like its actually the date sorting feature in the in-game spreadsheet, if you click on the date header it doesnt actually sort past the first page, and clicking it again sends you back to the first page.

**Comment by reconman** [comment]
I have no idea why it stopped working, I switched to another date sorting library in order to fix the issue.
