### ISSUE TITLE
Multiple Twitch Chat Tabs Opening

### ISSUE THREAD

**Issue by Leurus** [synkarius/saltbot#210]
Hi, first of all I want to say I love the bot. It's been so fun to play around with genetic weights especially.

An issue started happening today though. Saltbot keeps opening twitch chat tabs every minute despite there already being one open. Anyone have any idea why this is happening?

I noticed on the main saltybet page that the twitch chat that's normally on the right side is gone. This happened at the same time as the new tab glitch started happening. Could this be the cause somehow?

**Comment by Leurus** [comment]
No adblocker. I'm using a standalone Chrome installation just for Saltbot, so there's no other extensions installed.

**Comment by calexil** [comment]
fixed
