### ISSUE TITLE
Can't import chromosome and data

### ISSUE THREAD

**Issue by KaliNetKiller92** [synkarius/saltbot#213]
Another problem is that i can't import on any txt files on my Linux VPS (don't know why)

it works on chrome for windows but not on chrome for linux :/

I import the data from my linux, set the right on the file and try to import in saltbot but it did nothing.

**Comment by reconman** [comment]
Already fixed with #212

**Comment by calexil** [comment]
seems to be working fine on y mint betting box. can you do me a favor and try opening up the inspector over the 'import' button, check the console when you import and report it here

**Comment by KaliNetKiller92** [comment]
Quite weird, it does nothing last time, this time it's perfectly worked (well i upgrades my system  before)
I had the file read successful 👍

By the way thx for the help  :)
