### ISSUE TITLE
README.md has broken link to match data

### ISSUE THREAD

**Issue by douknoukkem** [synkarius/saltbot#219]
It has a link to https://github.com/synkarius/saltbot/blob/master/data/records%20and%20chromo%203-25-2018.zip

To make things easier for new people, maybe you can add a button to quick download and import data. And maybe show the total g() number instead of resetting the count after every run. I'm running Saltbot 24/7 minimized and exporting records here daily if anyone finds it useful: https://chiru.no/u/saltbot-records.txt https://chiru.no/u/saltbot-chromosomes.txt

**Comment by calexil** [comment]
d7fa7ab

resolved
