### ISSUE TITLE
Data Import Suggestion

### ISSUE THREAD

**Issue by AaroPro** [synkarius/saltbot#220]
You can pull quite a bit of betting and tournament/matchmaking/exhib data from SaltyBet's history stats if you have Illuminati.  How about being able to copy/paste this information into different .csv files to be able to import into saltbot?  Or maybe a separate tool to take .csvs and transform them into the necessary .txt files?  Please let me know if you need an example of the data I am speaking of.  Technically speaking, with this you should be able to create a database of all the matches in SB and have a very simple to follow process on how to update manually based simply off last capture date.  Would be really nice to have EX8 in here.

For data example, in SB.com click Stats>Tournament Stats>Click on "(Matchmaking) Salty's Dream Cast Casino 6366" for example.  All 100 Matchmaking matches and their winners.  If I had a better idea of how the data would be organized from that to how the app likes it, maybe I'd be able to help further, but I haven't really coded in some time.  Also, not sure why the app wouldn't be able to access this information, but then again, I don't know Google's constraints on apps such as this.

**Comment by calexil** [comment]
there is a huge database of live stats here: 

https://chiru.no/u/saltbot-records.txt

and a constantly updated chromo here:

https://chiru.no/u/saltbot-chromosomes.txt
