### ISSUE TITLE
Failed to load resource and Uncaught (in promise) errors

### ISSUE THREAD

**Issue by Hemi177** [synkarius/saltbot#227]
So I only downloaded and started "using" (I've only been running it in Monk mode letting it record matches so far, haven't done anything else) Saltbot a couple days ago. I opened up the console today and noticed some error messages popping up (I will attach the errors I'm receiving in the screenshot), I'm not sure if they have been doing it the whole time or not. I do have adblock plus and ublock origin on chrome but I have them disabled on saltybet and twitch. As I said I haven't used basically any of Saltbot's functionality yet but I wanted to post about these errors once I noticed they were happening.
![Saltbot Errors](https://user-images.githubusercontent.com/36756691/57337435-4f3ad700-70f7-11e9-8856-152ac614e514.PNG)

**Comment by calexil** [comment]
looks like twitch api calls failing, lots of platforms have been having this issue lately, I think they are reworking their core. 

we will monitor this issue thread for more confirmations, please try again in a week or so when the api is running full bore

**Comment by Hemi177** [comment]
Just coming back to report that those same error messages are still popping up. As far as I can tell SaltBot seems to be recording matches correctly, but I still haven't used any of the other functionalities yet so I don't know of they're affecting those.

**Comment by reconman** [comment]
All those error messages are generated by the page itself, not Saltbot, I think.

Try loading the page in Firefox and look at the console output.

**Comment by Hemi177** [comment]
I did as you suggested @reconman and this is what appeared in the console
![More errors](https://user-images.githubusercontent.com/36756691/57730684-0212b400-7667-11e9-8f21-7a962ee6cce2.PNG)

**Comment by reconman** [comment]
The console errors are not produced by Saltbot and don't have any noticable effect.

**Comment by calexil** [comment]
these errors are not related to the bot
