### ISSUE TITLE
Cowboy always bets blue if both chars win rate under 50%

### ISSUE THREAD

**Issue by RockStarRei** [synkarius/saltbot#232]
Every single time, even if red has a higher win rate under 50%. Cowboy should always bet higher win rate even if under 50%. Is there a way to adjust this? I assume it's a simple variable modification to strategy.js 223.

Also, Cowboy discourages betting under 50% and then no confidence bets anyway. This appears to be in strategy.js 156.

**Comment by calexil** [comment]
the project is open source, so feel free to fork it and test changing things around. If you come to a demonstrable improvement in accuracy, post a pull request.

**Comment by reconman** [comment]
Should be fixed with #5df5505

Now Cowboy doesn't bet if both characters have the same win percentage (0 %)
