### ISSUE TITLE
lunatic not betting

### ISSUE THREAD

**Issue by beachhouseshermgoblinoasisretretreat** [synkarius/saltbot#233]
hi guys its poopybuttholekilla from reddit im not really sure how to do bug reports but if u can guide me to the process thatd be chilled . basically i dont have any problems with scientist and cowboy mode so i've been using cowboy but i always preferred lunatic more in the genesis days of salt bot . what can i do to make it work and how come it stopped working ? i have ad block turned off also on saltybet and my saltbot and chrome is up to date

**Comment by elletheduck** [comment]
Also having the issue.  Win10, Chrome, downloaded chromosomes and records from sept and imported.  Ad block off.  Ran 20 matches in exhib (enabled) to see if it was a glitch or lack of salt, still did not pick up as a bet.

Cowboy has a 25% bet rate, 5 /20 placed bet and all on blue.  Scientist is lower with 3/20 picking up for bets, also all on blue.

**Comment by elletheduck** [comment]
Adding: the issues seem to be in the exhibition mode.  Running it in matchmaking and using it in tourney works fine after letting it set up and run consistently for a few hours.

**Comment by reconman** [comment]
Fixed by a55a4adc257d3b6b78545562ddffe8d8c36f595a
