### ISSUE TITLE
Bot only betting blue or not betting at all.

### ISSUE THREAD

**Issue by Alateriel** [synkarius/saltbot#234]
Issue: Bot has only been betting on blue for several days (since installation)

1. Download SaltyBot off of the Google Extension Store
2. Let the bot run in Scientist mode for a few days (this was observed at approximately 1,400, 2,000, and 4,900 bets)
3. Switch to Cowboy mode and let it run for a few matches.
4. Switch to Lunatic Mode and let it run for a few matches.

Results:
When running in Cowboy Mode the bot consistently bets 10% earnings on blue
When running in Scientist mode the bot consistently bets $8500 on blue (this value might change with higher/lower balances
When in Lunatic mode the bot doesn't bet at all.

Additional notes:
I've repeatedly reset my genetic algorithm and let it generate for approximately 50 iterations, at one point letting it generate overnight.

Attached is my up to date records log (as of 10/31/2019 3:30 AM) as well as my latest chromosome (that I let generate overnight)

[chromosome--2019-10-31-3.30.txt](https://github.com/synkarius/saltbot/files/3792597/chromosome--2019-10-31-3.30.txt)

[saltyRecordsM--2019-10-31-3.30.txt](https://github.com/synkarius/saltbot/files/3792598/saltyRecordsM--2019-10-31-3.30.txt)

**Comment by calexil** [comment]
1: the version on the extension store is extremely out of date

2: ...
