### ISSUE TITLE
records import doesn't seem to work

### ISSUE THREAD

**Issue by tycho** [synkarius/saltbot#237]
Trying to import a records file, and I'm getting this:

```
Attempting records import...
popup.js:116 Upload successful.
popup.js:121 Attempting to read file...
popup.js:103 File read successful.
popup.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

From what I can tell, the `ir` function in records.js never executes, because the message passing seems to fail. I stepped through the code after starting an import, and it seems to get through the `chrome.tabs.sendMessage` call below before printing the error above.

```
var btnClicked = function (clicktype, data = null) {
    data = data || null;
    chrome.tabs.query({
        active: true,
        currentWindow: true,
    }, function (tabs) {
        chrome.tabs.sendMessage(tabs[0].id, {
            text: data,
            type: clicktype,
        }, function (response) {
            if (response && response.farewell) {
                console.log(response.farewell);
            }
        });
    });
};
```

I've never worked on a Chrome extension so I'm not sure where to begin on debugging something like this.

**Comment by uche667** [comment]
idk

**Comment by calexil** [comment]
tested three different recent versions, all importing correctly. this is isolated to you unfortunately. closing
