### ISSUE TITLE
Scientist selection does not seem to work

### ISSUE THREAD

**Issue by DayOfTheJackal** [synkarius/saltbot#28]
Selecting the scientist option in the dialogue doesn't seem to change the betting strategy, the other options work fine.

Expected: Console echoes that the strategy has changed.

Actual: There is nothing echoed to the console and the strategy is not changed.

**Comment by DayOfTheJackal** [comment]
Appologies, I hadn't correctly set up the chromosome pool.

As an side, some feedback in the console might be a nice addition, but it's my own fault.

**Comment by synkarius** [comment]
User experience is important. When would you expect to see something in the console-- when you select Scientist and haven't set up the chromosome pool yet?

**Comment by reconman** [comment]
Yes, that would be great. I've had this exact problem too.

**Comment by synkarius** [comment]
I have added a message for when you try to select scientist but haven't set up the chromosome pool.
