### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by saltydude** [synkarius/saltbot#29]
Is there any way to get this working in firefox? Would like to run this on my VPS but Chrome doesn't work well in an OpenVZ environment. 

Thanks.

**Comment by synkarius** [comment]
The decision-making logic and UI control could be ported easily, but I don't have the time to learn the Firefox extension API right now. If you know someone who already knows it, or who's willing to learn it, I'd happily offer guidance on the rest of the porting process.
