### ISSUE TITLE
Tournament mode is not flexible for Levels and Illuminati status

### ISSUE THREAD

**Issue by reconman** [synkarius/saltbot#30]
In strategy.js you hardcoded 1000 and 2000 for tournament mode. With higher levels the amount you get at the beginning of tournaments increases, especially for Illuminati.

Can you somehow detect the current level and illuminati status and use the calculated starting amount as basis for your tournament calculations instead of 1000?

You should also define something like
if (confidence > 0.9) {
  confidence = 1.0;
}
as betting 90% of all your tournament balance doesn't really make sense.

**Comment by synkarius** [comment]
Both of those things are possible, and pretty good ideas. I don't know how to detect illuminati status since I'm not illuminati, but I could put a checkbox in the SaltBot UI to indicate that you're illuminati, or some illuminati member could tell me where in the SaltyBet UI it's different if you're illuminati.

If I get some time this weekend, I'll put those in.

**Comment by reconman** [comment]
The easiest way to detect Illuminati status is by looking up the class of the span-element around your username. In case of illuminatis the class is "goldtext" as seen in this screenshot.

http://puu.sh/ikbCy/260d866ab4.png

**Comment by synkarius** [comment]
Excellent. Thank you very much.

**Comment by reconman** [comment]
And the level can be determined from the span with the id "rank" which is in the screenshot too.

rank12.png -> Level 12

Using custom avatars as Illuminati does not replace the image but adds an image into the span with the class "nomargin" above.

**Comment by synkarius** [comment]
This is taken care of with version 1.9.3.

**Comment by reconman** [comment]
I just looked into the updated code and now it's something like this:

bailout = isIlluminati ? level*75 : level*25;
and then 1000 + bailout everywhere

Illuminati get 2000 + level * 50.

The easiest fix would be to write the getBailout function like this:
Strategy.prototype.getBailout = function(){
	var links = document.getElementsByTagName("a");
	var target = null;
	for (var i = 0; i < links.length; i++) {
		if (links[i].href === 'http://www.saltybet.com/options') {
			target = links[i];
		}
	}
	var isIlluminati=false;
	var level=1;
	if (target!=null){
		for (var k=0; k<target.childNodes.length; k++){
			var child = target.childNodes[k];
			if(child.classList && child.classList.contains("goldtext"))
				isIlluminati=true;
		}
	}
	var rank = document.getElementById("rank");
	if (rank!=null){
		var re=/rank([0-9]{1,2})\.png/g;
		var match=re.exec(rank.childNodes[0].src);
		level=parseInt(match[1]);
	}
	if(isIlluminati)
		return 1000 + level*50;
	else
		return level*25;
};

**Comment by synkarius** [comment]
So you understand JavaScript, have better information than I do regarding Salty Bet, actually have a Github account, but are averse to doing pull requests? ;-) Just kidding. Do illuminati get that same amount (1000 + level*50) at non-tournament times, or at non-tournament times is it (0 + level*50)?

**Comment by reconman** [comment]
I haven't worked with GitHub and pull requests yet. I only use it for reporting and looking into source code, so I have no idea how pull requests work.

I think it's 2000 + level * 50 so the tournament and normal starting salt amount should be the same. The site says "You will have a bailout amount of $2000 in addition to your level bonus". I can't say for sure because I have never been to the salt mines since I became an illuminati.

**Comment by synkarius** [comment]
I just updated the app on the chrome store. Chrome should update it automatically soon. Thanks again.
