### ISSUE TITLE
Bets blocked by Uncaught TypeError

### ISSUE THREAD

**Issue by coinop** [synkarius/saltbot#49]
When set to cowboy or scientist I can't seem to get any bets in, the console spits out:

Uncaught TypeError: Cannot read property 'classList' of undefined
Strategy.getBailout @ strategy.js:15
Strategy.getBetAmount @ strategy.js:75
Match.betAmount @ tracker.js:82
(anonymous function) @ tracker.js:132

**Comment by synkarius** [comment]
Thanks for the heads up. The recent Salty UI changes broke a lot of stuff with the bot. It should be fixed as soon as version 1.10.2 hits the Google Store. (Sometimes there's an hour lag.)

**Comment by coinop** [comment]
Thanks for the swift resolve, testing from src right now
