### ISSUE TITLE
Ideal genetic weights found?

### ISSUE THREAD

**Issue by reconman** [synkarius/saltbot#50]
I'll leave this here if you want to change the initial genetic weights. After several generations no better weights can be found.

> this.oddsWeight = 1.8549966520931462;
	this.timeWeight = 1.1031189409244249;
	this.winPercentageWeight = 2.9077989478042916;
	this.crowdFavorWeight = 0.005112205084118831;
	this.illumFavorWeight = 0.0009473630531161294;
	this.minimumCombinedConfidenceForLargeBet = 0.48436656617494533;
	this.minimumMatchesForLargeBet = 4.010238368527831;
	this.useMinCon = 0.09207601707935577;
	this.useMinMat = 0.11168438672383378;
	this.useSimilarAbility = 1.5940199534268533;
	this.wX = 75.72081773128612;
	this.wS = 4.446050435498266;
	this.wA = 0.3958316441822831;
	this.wB = 0.21452716623874007;
	this.wP = 56.30064815598871;
	this.wU = 0.3284199607517061;
	this.lX = 0.031386742689349045;
	this.lS = 0.0528898832275746;
	this.lA = 0.23679703153685597;
	this.lB = 1.310069078919525;
	this.lP = 1.3497754158286093;
	this.lU = 0.5759811344280866;
	this.oX = 18.018743043251796;
	this.oS = 50.359728703405466;
	this.oA = 1.0130400620460684;
	this.oB = 11.525905368908644;
	this.oP = 1.0639248762090212;
	this.oU = 2.8625219602163847;
	this.wtX = 29.006814043297485;
	this.wtS = 0.24564509064194154;
	this.wtA = 1.6515435777948981;
	this.wtB = 0.02434766938025773;
	this.wtP = 0.6999303551497656;
	this.wtU = 0.1945792668725041;
	this.ltX = 30.011088094612226;
	this.ltS = 40.99241754969083;
	this.ltA = 5.174790332614436;
	this.ltB = 0.4423742809713067;
	this.ltP = 0.8504435722652295;
	this.ltU = 0.6809271710393173;

**Comment by synkarius** [comment]
Admittedly, that chromosome does work really well, but that could change. Let's say more characters get added, as seems to happen from time to time, or the illuminati buff or debuff characters. Better yet would be this feature which I've thus far been too lazy to implement: https://github.com/synkarius/saltbot/issues/23

**Comment by reconman** [comment]
Am I correct to assume that the chromosome is stored in chromosomes_v1?

**Comment by reconman** [comment]
The only thing you need to do is to stringify the chromosomes in chromosomes_v1 and save them to a file like for the records, right? And when you import them you just read the file again.

**Comment by synkarius** [comment]
Correct you are, sir. Doing that and updating the UI with import/export buttons is what such a feature would consist of.

**Comment by reconman** [comment]
Sounds easy enough. I may implement it in the next few days. 

Am 22. Juli 2015 02:58:10 MESZ, schrieb David Conway <notifications@github.com>:

**Comment by synkarius** [comment]
I should also mention, chromosomes_v1 always has the top 20 chromosomes in it. If you overwrite 0-th position in that list with the imported chromosome, that will cause it to be the chromosome that sendUpdatedChromosome() sends to the *.saltybet.com tab.

**Comment by saltydude** [comment]
Is this still the most recent good chromosomes? Nice tournament win BTW.

**Comment by reconman** [comment]
I've found a slightly better chromosome which I've added to the repository.
