### ISSUE TITLE
Don't record exhibition matches

### ISSUE THREAD

**Issue by reconman** [synkarius/saltbot#52]
Exhibition matches should not be recorded as users deliberately choose weaker characters with advantages against strong characters. One example would be 12P versions of usually weak characters who are as strong as X-Tier characters.

**Comment by synkarius** [comment]
I did get around to testing this. Removing all exhibition matches from the records and loading them back in made virtually no difference. Did you get different results? If so, I'll test again, more thoroughly. I only did 30 generations twice per records import (one with "e" type matches, one without, so four runs of 30 generations total).

**Comment by reconman** [comment]
Removing the exhibition matches leads to about 2 million less selt for me so they can be recorded. At least the team matches aren't recorded anymore. Saltbot doesn't bet on them anyway.
