### ISSUE TITLE
UI mostly not working.

### ISSUE THREAD

**Issue by xThyArmageddonx** [synkarius/saltbot#54]
By the looks of it, aside from importing records, there's a problem with the UI accepting inputs when you click on an option.  After right-clicking on the UI to look at the console, it's giving me this error:

Uncaught TypeError: Cannot read property 'addEventListener' of null

If I click to see where the error is coming from, I'm directed to this line which is highlighted in red:

document.getElementById("bsc").addEventListener("click", function() {

I have very little knowledge on coding and programming, but I love the bot and the app and figured I'd help if I could, provided this hadn't already been noticed.

**Comment by reconman** [comment]
Thank you, at the last commit @synkarius changed the UI layout. A few important things were removed so it doesn't work correctly right now. I'll try to fix it and you can expect synkarius to publish it in about 6 hours.
