### ISSUE TITLE
Match.prototype.update() sometimes doesn't work

### ISSUE THREAD

**Issue by synkarius** [synkarius/saltbot#55]

**Comment by reconman** [comment]
Sometimes twitch_content.js doesn't load at the twitch.tv tab and then no waifu messages are received. The only fix is to reload twitch.

Is this related to your bug?

**Comment by synkarius** [comment]
This is probably caused by interference from other Google Chrome plug-ins. The guy who reported it did so on my website, so I'm going to wait to hear back from him there before closing it, but I've been able to reproduce and stop it by enabling and disabling other plug-ins.
