### ISSUE TITLE
Saltbot stuck betting 0 on blue

### ISSUE THREAD

**Issue by LordAbortion** [synkarius/saltbot#59]

**Comment by synkarius** [comment]
Did you import the seed data?

**Comment by LordAbortion** [comment]
I did, give me a few to let it gather another few dozen generations and I'll get a screen, attempts to get things functional again caused things to start over

**Comment by LordAbortion** [comment]
![image](https://cloud.githubusercontent.com/assets/13615509/9028917/10e78b0c-3946-11e5-8ee5-930faa5787f9.png)

**Comment by synkarius** [comment]
Your seed data and didn't import correctly. You only have 237 matches. You should have over 23,000. Try importing it again.

**Comment by synkarius** [comment]
Incidentally, you need to import the text file, not the zip. If it works, it should actually make Chrome freeze for a few seconds.

**Comment by synkarius** [comment]
No, I'm sorry, that's 237 generations. You only have 9 matches.

**Comment by LordAbortion** [comment]
Good observation, any idea on how to ensure chrome imports the txt correctly? I think I got it to import correctly, but whenever I click update genetic weights, it seems to freeze the plugin menu.

**Comment by synkarius** [comment]
I don't know how to ensure it imports correctly, except that if it fails, just try again. If "Update Genetic Weights" freezes the UI, that's good -- let it do its work. That freeze is an indication that it's functioning correctly. It will unfreeze for fractions of a second between generations.

**Comment by LordAbortion** [comment]
Seems to be working okay, betting only hundreds though, and when I click outside the frozen js window, evidently that forces it to switch to monk? Nothing aside from - Monk does not bet appears in the console so I can't be sure.

**Comment by synkarius** [comment]
The bot bets conservatively. If you want it to bet more aggressively, click "Toggle Aggro." If the switching to Monk thing happens regularly, open another bug for it.
