### ISSUE TITLE
Will no longer let me import records/chromosome.

### ISSUE THREAD

**Issue by Spoondune** [synkarius/saltbot#63]
Had this up and running just fine, had to reformat my computer. Saved two copies of my records, yet I cant get the extension to import them for some reason. Never had this issue before, not sure how to trouble shoot it. Tried to upload the seed data just to test, screen pauses like its going to import but then it doesnt. No message in the developer console confirming successful import of records either. 

Any help?

**Comment by Spoondune** [comment]
Never had this issue before..not sure how to troubleshoot.

**Comment by Spoondune** [comment]
I cant even update genetic weights now, something odd is going on.

**Comment by synkarius** [comment]
Right-click somewhere on the SaltBot UI, select "inspect element". Click on the console tab. Try to import them again. What messages do you get in the background window console?

**Comment by synkarius** [comment]
Did you get this working? If not, please read [the bugs guide](https://github.com/synkarius/saltbot/blob/master/doc/bugs.MD) and give me the information requested.

**Comment by Spoondune** [comment]
Yes. I got it working. It was just an odd fluke. Up to 1,214,654 currently. Bot works fine!

Date: Sat, 3 Oct 2015 07:51:30 -0700

**Comment by synkarius** [comment]
Glad to hear it!
