### ISSUE TITLE
Stop betting after reaching $______

### ISSUE THREAD

**Issue by db-kai** [synkarius/saltbot#64]
Since I have old data (no data), I want saltbot to bet until it 'gets lucky'.  So it'd be useful to have saltbot engage monk mode after exceeding a user defined amount.  This way new users don't need to wait weeks for saltbot to gain experience.

**Comment by synkarius** [comment]
Doesn't this also prevent you from getting lucky twice?

**Comment by db-kai** [comment]
It just ensures that saltbot doesn't lose what you want to keep.  If it
reaches 100k, I'd like for it to keep that.

It does lose quite a bit in my experience.  I feel like it default bets
blue when it has no data on the combatants.  It's more reliable when aggro
isn't toggled because it conserves money but it still has the potential to
lose any significant amount it makes.  If I can toggle aggro and it
magically wins 10 matches in a row at some point during the day, I'll have
some amount to have fun with.  I'm sure the bot will gain accuracy as I use
it but for now, I'm relying on its luck.  (it's been running for a solid
week now)

I just think it's a useful feature for new users.

**Comment by db-kai** [comment]
Also does cowboy not look at the win/loss ratios given to illuminati?  It
doesn't seem to consider them at all.

**Comment by reconman** [comment]
No strategy considers the win rates given to illuminati. It provides no information about in which tier the wins/losses were made.

**Comment by db-kai** [comment]
I see!  Thanks for the insight~

**Comment by synkarius** [comment]
@db-kai You mentioned having no data. Are you using the seed data zip file?

**Comment by db-kai** [comment]
I used it but found the data was too old.  I built up 2 months of data and
accidentally got it erased when taking saltbot off of one of my computers.

**Comment by db-kai** [comment]
This...this is what I'm talking about.  I'll have it set to aggro while I'm monitoring it (this is an easy way to get a lot really quick).  I'll go to sleep after I all in the wrong match- then I come back in the morning to this...  

![dammit saltbot](https://cloud.githubusercontent.com/assets/14299133/10578622/3841329c-7641-11e5-83c7-32373e85dcf0.png)

I think it would be nice if it stopped betting after making six digits on aggro.

**Comment by db-kai** [comment]
Is this idea no good?  I have data now but I still want to have it stop betting after reaching a certain point.  Here are my records btw: 
[saltyRecordsM--2016-0-15-13.53.txt](https://github.com/synkarius/saltbot/files/92347/saltyRecordsM--2016-0-15-13.53.txt) 
This is all data from October to now.  Excluding a handful of times my computer decided to shut down in the middle of the night.

**Comment by reconman** [comment]
It's not a bad idea, that's for sure. I only had no time/motivation for adding it to the saltbot yet. I'll try adding it in the near future.

**Comment by db-kai** [comment]
That would be amazing!

**Comment by reconman** [comment]
There's now a checkbox and input field for defining the limit. Please note that you have to click out of the textfield to register the change of values. The limit state can be observed in the console.

@db-kai Please wait until synkarius has updated the extension before reopening the ticket. The new version number should be 2.1.0.

**Comment by db-kai** [comment]
Coming back this morning and seeing my request made reality was the best
thing ever.  Thank you so much!
