### ISSUE TITLE
No wager is entered before selection

### ISSUE THREAD

**Issue by MoffMade** [synkarius/saltbot#65]
Tried running on Cowboy and Scientist. It tries to select a team, but all that pops up is "Please enter a wager." The developer console gets this message

Uncaught TypeError: Cannot read property 'src' of undefined
Strategy.getBailout @ strategy.js:25
Strategy.getBetAmount @ strategy.js:81
Match.betAmount @ tracker.js:82
(anonymous function) @ tracker.js:132

**Comment by synkarius** [comment]
I am unable to reproduce this error. Please read [the (new) bugs guide](https://github.com/synkarius/saltbot/blob/master/doc/bugs.MD) and give me more detail.

**Comment by OldDragon2A** [comment]
I ran into this one.  It happens when you don't have a rank.  In strategy.js:31, rank.childNodes is empty.

`<span id="rank" class="nomargin"></span>`

**Comment by reconman** [comment]
Duplicate of #91
