### ISSUE TITLE
Request: No bets for exhibitions

### ISSUE THREAD

**Issue by PapaNovember** [synkarius/saltbot#66]
Considering that most exhibitions these days are traps in ways a bot won't understand, it would be nice to shut off or greatly reduce confidence on exhib matches.

**Comment by synkarius** [comment]
This sounds like it might be better as an option, right? If I flat-out shut them off, we'd have someone in here next week asking for them to be turned on.

**Comment by PapaNovember** [comment]
Yeah, I kind of envisioned it as an option, although I don't know how much of a UI pain in the butt that would be.  Or just "insert this code into the salty.js here" :)  I'm not clever enough to figure it out myself.

Thanks for the cool job making this thing, by the way!

**Comment by Celestiae** [comment]
Can I ask if there's any update on this, or whether it's actually possible at all?

**Comment by Zyrixion** [comment]
This was actually the first thing I coded into my experimental branch, being that it tended to hemorrhage salt during exhibs.  I think it'd be a worthwhile thing to make into a toggle, I might take a look into it sometime but I do not know when, since I would have to uproot my own files/version to test it.  It would be somewhat easy to do, at least.

**Comment by PapaNovember** [comment]
Ooo thanks Zyrixion -- looking at your branch I think I could at least do it for my own installation.  Not the toggle but at least implementing the exclusion.

**Comment by Zyrixion** [comment]
Yeah it shouldn't actually be all that difficult, feel free to raise an issue on my branch if you end up having difficulty doing so.  I'll actually go ahead and commit my current build to the branch, so I know that the code is actually consistent with what works on my side, but I would not advise using the branch itself, it has thus far failed in its aim to do better than the original script, but at least the anti-exhib code is useful.  The only hiccup is that it occasionally lets the first exhib match go through if it's not a team match, which, I know why but it's not something I have a reasonable way to fix without rethinking how I implemented it as it is.

**Comment by reconman** [comment]
I'm working on a solution right now. It's a bit hard to test since exhibitions take place only every 4 hours or so. As soon as I get a running version I will commit the change.

**Comment by PapaNovember** [comment]
Awesome reconman!  Yes, Zyrixion, I managed to alter it on my own .js, but I'm sure others would appreciate it being on the official once reconman can do it.  Getting Chrome to accept altered extensions without freaking out can be a bit of an adventure these days.

**Comment by reconman** [comment]
It's so annoying when you get a message about extensions in developer mode every time you start Chrome...

**Comment by reconman** [comment]
@synkarius Could you please build a new extension version with my latest commit? I've tested it pretty intensively.

With this changes you can toggle the exhibitions with an additional button in the UI. I don't know for sure if it works on the first exhibition round but it works on all other rounds.

**Comment by synkarius** [comment]
@reconman It's uploaded, should update within an hour. As always, thanks for handling those requests.
