### ISSUE TITLE
Not recording all match data/possibly not pulling messages from Waifu4u

### ISSUE THREAD

**Issue by Ampheric** [synkarius/saltbot#67]
Chrome version: Version 46.0.2490.71 m (Also tried latest dev version)
OS: Windows 7 Ultimate 64 bit.

I used the bot several months back before it was added to the chrome extension store, and it worked flawlessly. Just come back to Salty Bet and using the bot in the last few days and noticed it doesn't seem to be pulling messages from Waifu4u, or atleast it's not properly recording match statistics as shown in this [screenshot](http://i.imgur.com/PfM3bno.png).

I snooped around the dev console and background window but it wasn't logging any errors. Loaded the extension up on the latest dev release of chrome and managed to come across these two  [errors](http://i.imgur.com/pegkcid.png). One being on [line 6 of twitch_content.js](http://i.imgur.com/SJJ6FXI.png) and the other one on [line 55 of twitch_background.js](http://i.imgur.com/b2vdwfJ.png).

Since I'm clueless about coding I figured it would be best to open up an issue and hope you can direct me in some way on how to fix said errors and get the bot working again.

Thanks a bunch and great work.

Quick edit; I should mention I have tried running the bot with no other extension enabled or even installed.

**Comment by reconman** [comment]
Thank you for reporting the issue. It's probably because twitch changed their player from flash to HTML5. The Javascript can't find the HTML elements anymore and throws errors.

**Comment by Ampheric** [comment]
Thank you for the response. I was getting a feeling it was from the change in player.

**Comment by Ampheric** [comment]
Seems to be working all fine now, thanks for the fixes.
