### ISSUE TITLE
Not Detecting Illuminati/Gold?

### ISSUE THREAD

**Issue by cjXDD** [synkarius/saltbot#68]
Just started using saltbot, has been working great. I have noticed though when using it on cowboy to build up data that it doesn't bet the right amount? It seems to bet 2,250 instead of 3,250 which is my correct bailout. Is there a reason why it doesn't bet max when on verge of getting bailed out? I looked at strategy, and it says of illuminati, then 2,000 lvlx50. But it should be 3,000 lvlx50 ? Tried to change it, crashed. Bug or am I stupid? Thanks.

**Comment by synkarius** [comment]
Uploaded. Thanks @reconman.
