### ISSUE TITLE
Missing data/character tiers?

### ISSUE THREAD

**Issue by Zyrixion** [synkarius/saltbot#70]
What exactly is the format for the records output?  Because by what I can tell, it is not finding/recognizing/saving tiers for characters, at least by what I see in the output file, and the console logs are no longer verbose, as they were in the screenshots in the 'about' page.  For reference, a short bit of my export log follows:

Zabi,Shadow diavolo,0,obs,a,U,U,U,0,2,2
Yukkuri,Naruto kun,1,obs,a,U,U,U,0,2,2

It obviously shows winner, but none of the other values change at all for any of the recorded fights, which leads me to believe it is missing a LOT of data.

**Comment by synkarius** [comment]
Please read [the bugs guide](https://github.com/synkarius/saltbot/blob/master/doc/bugs.MD) and give me more detail.

**Comment by Zyrixion** [comment]
Apologies, I of all people should have realized that was an awful bug report.
OS: Win7 Home Premium x64
Chrome Version: Version 46.0.2490.86 m (latest)
Installation steps and initial usage:  I installed the extension via the Google Play store, but decided to build my own matchup history from scratch instead of starting with very old data, so I enabled 'Monk' mode and let it do its thing (I did let the twitch.tv tab remain open as instructed in the usage guide).  When I did an export to test that it was outputting data correctly, I noted that I couldn't find the tier data, and after letting it go longer, and having all data turn up the same, I figured it wasn't correctly catching tier data.  A bit more digging to figure out the actual formatting and I found it was marking all the tier data as 'U' for unknown, and that led me here.
Console errors from saltybet.com dev console:
JQMIGRATE: jQuery.browser is deprecated

global-906553aedfcf3a421af19e4dc0c7d639.js:15 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED

global-906553aedfcf3a421af19e4dc0c7d639.js:30 No cast extension found

global-906553aedfcf3a421af19e4dc0c7d639.js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.

global-906553aedfcf3a421af19e4dc0c7d639.js:30 TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.

emberchat-11f6dc4e8faba9aa66168beabde5462a.js:27 Uncaught SecurityError: Blocked a frame with origin "http://www.twitch.tv" from accessing a frame with origin "http://www.saltybet.com". The frame requesting access set "document.domain" to "twitch.tv", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.

s-dal5-nss-41.firebaseio.com/.lp?dframe=t&id=8841614&pw=JGtNqrvhPx&ns=ttv-23:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Error messages from twitch.tv tab dev console:
JQMIGRATE: jQuery.browser is deprecated

global-906553aedfcf3a421af19e4dc0c7d639.js:15 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED

global-906553aedfcf3a421af19e4dc0c7d639.js:30 No cast extension found

2http://api.twitch.tv/kraken/users/zyrixion/follows/channels/saltybet?on_site=1 Failed to load resource: the server responded with a status of 404 (Not Found)

http://api.twitch.tv/api/channels/zyrixion/payout_entity?on_site=1 Failed to load resource: the server responded with a status of 404 (Not Found)

chrome-extension://bholoegapebhflljekancpcnajigaiih/twitch_content.js:6 Uncaught TypeError: Cannot read property 'childNodes' of undefined

s-dal5-nss-41.firebaseio.com/.lp?dframe=t&id=8857233&pw=OUAbzxH3Fi&ns=ttv-23:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.

**Comment by reconman** [comment]
It's probably because the javascript on the twitch tab always failed. My last commit should have fixed this but I'm not too sure if the rest of saltbot is currently working correctly.

**Comment by Zyrixion** [comment]
Ah, well.  While I do know programming I know nothing of using github or messing with chrome extensions, so it would take a bit of help to apply the fix, if applicable.

**Comment by synkarius** [comment]
I just pushed @reconman's fix to the Chrome Store. @Zyrixion, that should be up within an hour or two. Thanks much @reconman!

**Comment by Zyrixion** [comment]
Alright, while that did fix the issue where it wasn't killing the video, the issue I was having with match data remains, but the errors on the twitch.tv page changed (the ones on the saltybet.com page did not change).  They follow:

JQMIGRATE: jQuery.browser is deprecated

chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED

global-906553aedfcf3a421af19e4dc0c7d639.js:15 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED

chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED

global-906553aedfcf3a421af19e4dc0c7d639.js:30 No cast extension found

2http://api.twitch.tv/kraken/users/zyrixion/follows/channels/saltybet?on_site=1 Failed to load resource: the server responded with a status of 404 (Not Found)

http://api.twitch.tv/api/channels/zyrixion/payout_entity?on_site=1 Failed to load resource: the server responded with a status of 404 (Not Found)

Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "http://www.twitch.tv".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

s-dal5-nss-41.firebaseio.com/.lp?dframe=t&id=12488161&pw=jzWeGp2MED&ns=ttv-23:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

player.js:2 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.



And a new error, which I presume to be the source of the issue:

chrome-extension://bholoegapebhflljekancpcnajigaiih/twitch_content.js
Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.

When I tracked it, it led to line 49 of code in the Saltbot twitch_content.js:

observer.observe(chatWindow, {

**Comment by Zyrixion** [comment]
So, I'm not saying that this is why for sure it is failing but this is what I found while trying to trace the origin of the error.  The first catch to try to hook the chat in the twitch.tv code is:

var chatWindow = document.getElementsByClassName("scroll chat-messages js-chat-messages")[0];

But the class for me appears to be:

<div class="scroll chat-messages js-chat-messages showTimestamps showModIcons">

(which obviously has permutations where timestamps and mod icons are combinations of off or on)

This all said, I don't know javascript or if that kind of call actually should work, but it LOOKS like it shouldn't find it to me.  And of course there's still the second part, where it tries to get it by element ID but I guess that fails too since chatWindow appears to still be null by the time the observe function is called on it.

**Comment by reconman** [comment]
Thanks for your detailed report. I found out that the chat window seems to be loaded asynchronously. The chat appears a few seconds after the site is loaded, that's why the script can't find it.

I've changed the code to wait for the chat and video to appear instead of assuming they are already there.

I will commit a fix in a few hours and @synkarius will update the extension on the chrome store.

**Comment by synkarius** [comment]
Updated. Thx.

**Comment by Zyrixion** [comment]
Just wanted to come back and confirm that this issue has indeed been solved.  Thank you guys very much for your correspondence here.  :)
