### ISSUE TITLE
Page no longer auto-refreshing?

### ISSUE THREAD

**Issue by Zyrixion** [synkarius/saltbot#71]
I noticed before the last version there that fixed the previous issues I was having before, and as it was noted in the usage guide, it was auto-refreshing the page every 25th match (it was easy to notice because the console output told how many matches had been saved since the page was opened).  However, now it is no longer doing so, as I noticed when I woke up this morning and saw it was on match 88 of the cycle- but the reason I mention it is because all of the recently recorded matches at that point were missing the tier/etc information.

Now, that all said I haven't been able to reproduce the part of the bug where it stopped correctly catching match data (but it certainly doesn't auto-refresh every 25 matches), but I'm leaving it open again to see whether it does in fact start leaving out data again.  I also don't know what the purpose of refreshing the pages every 25th match is, but I assume there was a good reason for doing it.

EDIT: Closing until such point that I am able to reproduce the bug I had, and am sure it was not caused by an unloaded twitch.tv tab

**Comment by synkarius** [comment]
The auto-refresh keeps you logged in permanently and prevents a certain kind of crash. The number was bumped from 25 to 100. It's only an error if you see the cycle number go over 100.

**Comment by reconman** [comment]
@synkarius That's not the error he mentioned, only that the saltybet-tab-script won't receive anything after a refresh.

**Comment by synkarius** [comment]
@reconman Ah, whoops! Correct you are. @Zyrixion Thanks for reporting it, even if it's difficult to reproduce.

**Comment by Zyrixion** [comment]
Thus far it hasn't recurred, and I am thinking that the error may have been generally unrelated to the script, and was perhaps just failing to entirely load the twitch.tv page after restarting chrome, since I restart my last tabs on start and if the saltybet twitch.tv page exists, it won't create another, regardless of whether it is fully loaded or not.  Like I edited into the first post, I'm not sure this is an actual issue yet since I cannot get it to recur, though at the time I thought differently.  I'm certainly keeping an eye on it though.
