### ISSUE TITLE
[Suggestion]  Using specific matchup data for weighting?

### ISSUE THREAD

**Issue by Zyrixion** [synkarius/saltbot#72]
It occurs to me that probably the one way left to increase the accuracy of the bets, is to use the results of past iterations of the same matchup between characters to help weight which side gets bet on (assuming it doesn't already, which by what I gathered it doesn't).  I'm sure this would be a rather complicated addition, but I think has the potential to push accuracy to higher levels.

On an unrelated note, the stuff here on github is identical to the chrome store addon, yeah?  I was considering playing with this concept myself, but wanted to make sure I would have relevant code to work with.

**Comment by synkarius** [comment]
We tried creating a giant ranking list some months ago, such that if A beat B and B beat C, it would stand to reason that A should beat C. There were a few problems.

* there are 6000+ characters and even with full historical data, there's no guarantee that a full ranking list can be built without gaps
* rock-paper-scissors ranking triangles
* higher accuracy doesn't necessarily lead to more money

However, to answer your question, yes, this is the exact source code of the Google Store app. So if you do manage to find a solution to those problems, please put in a pull request.

**Comment by DarkDot** [comment]
What about more as system identification, it seems that certain fighting styles are better against others so you get the triangles but with large data sets it should be possible to identify the fighter characteristics and classify them for weighting.
