### ISSUE TITLE
Cowboy mode

### ISSUE THREAD

**Issue by Celestiae** [synkarius/saltbot#75]
While I'm not too sure if this us an error or not, I'm still quite confused on how cowboy mode actually works. Supposedly it should be going with the higher percentage, but it seems to be hit and miss; siding with a 6% instead of 46%, and such. Occasionally it'll get a win but most of the time it loses since it sides with lower percentage. I did read the post about it, so I'm not quite too sure.

**Comment by Zyrixion** [comment]
Just to be clear, are you looking at the character win percentages in the illuminati stats page/display?  If so, note that the script doesn't pull from that, instead using data it has recorded as it watches/bets on matches, meaning that it's entirely possible that while char 1 has a higher win percentage than char 2 in total, the matches the script has recorded may paint the opposite picture.

**Comment by Celestiae** [comment]
I see. How long should I leave monk open for there to be some reliable results?

**Comment by synkarius** [comment]
As of this time last year, there were 5000+ characters. One recorded match is one win/loss for each of two characters. I'd say wait at least a few thousand matches or just use the seed data. Yes it's old, but that probably only matters for a small handful of the characters which the illums have adjusted the stats on drastically. Most characters are probably at their same power levels as they were a year ago.

**Comment by Zyrixion** [comment]
There are approximately 6240 characters, and I didn't start having reliably having much data on the usual chars to be seen until about 15,000 to 20,000 matches.  As well, results would not be entirely reliable even with the almost 40,000 matches I have recorded as of now, as the winrate for characters is only an extremely rough estimate of their level of power.  In fact I've been working for months on an experimental branch to try and figure out a more precise way of determining the actual power of characters, and have so far been more or less trumped by just following a comparison of the average odds for each character, which is itself also not entirely reliable.  At any rate, scientist will probably produce the best results for you, given that both it and cowboy require comparable amounts of data anyhow.

**Comment by Celestiae** [comment]
In that case, should I stick with the recommended 5000 games for Scientist to be effective?

**Comment by Zyrixion** [comment]
Yeah, that's about when I started using scientist, I just ran monk until I had the matches.  I might see about getting synkarius my match data for a better seed file sometime or another.

**Comment by synkarius** [comment]
I would gladly replace the seed file if you have a large chunk of newer data.
