### ISSUE TITLE
[Suggestion] A way to increase bet amount automatically

### ISSUE THREAD

**Issue by zaccie** [synkarius/saltbot#79]
Currently, for me anyway Scientist bets too low and cowboy bets too high by default.
Enabling aggro bring the bet amount way too high on Scientist than I would like so I was thinking another button that doubled or tripled whatever bet the scientist would have made.

Example, I currently have 20k so scientist mode bets between $500 and $1000 on the couple of fights I have observed right now. I would like for him to be betting $1000-$2000 per bet instead.

**Comment by reconman** [comment]
I'll consider implementing it.

**Comment by zaccie** [comment]
Yeah sweet, it's no fuss just if you've ever got the free time it'd be really neat to have.
