### ISSUE TITLE
Confidence levels way out of wack?

### ISSUE THREAD

**Issue by theCreator111** [synkarius/saltbot#85]
After a PC restart, my confidence levels  have been far too high on the script and it's betting far higher numbers than I can break even with. I have had to turn off the aggro to supplement this.

If this can be looked into possibly that'd be great. I created my own data rather than using the data that Synkarius uploaded so I could get accurate data myself so the confidence levels shouldn' be this high!

I have all other extensions disabled so that shouldn't be the issue.

Here is a snippet from the log.

`extensions::uncaught_exception_handler:8Error in response to storage.get: ReferenceError: aggro is not defined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/salty.js:423:33)
    at chrome-extension://bholoegapebhflljekancpcnajigaiih/salty.js:416:23handler @ extensions::uncaught_exception_handler:8
salty.js:4 Activated browser action
salty.js:325 response received in salty
player.545ed41….js:35 Uncaught (in promise) undefined
player.545ed41….js:35 Uncaught (in promise) undefined
chrome-extension://fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js Failed to load resource: net::ERR_FAILED
https://edge.quantserve.com/quant.js Failed to load resource: net::ERR_INSECURE_RESPONSE
undefined:1 Uncaught (in promise) undefined
undefined:1 Uncaught (in promise) undefined
global-2638692….js:17 JQMIGRATE: Logging is active
global-2638692….js:17 JQMIGRATE: jQuery.browser is deprecated
global-2638692….js:15 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
global-2638692….js:30 No cast extension found
strategy.js:583 - Monk does not bet
emberchat-207ca21….js:34 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://www.saltybet.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: 353.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: 366.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: CAP.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: GLOBALUSERSTATE.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: 353.
global-2638692….js:30 TMI.js [irc] WARNING: Could not parse IRC message: 366.
(program):1 build: local
.lp?dframe=t&id=11440671&pw=ZxQMPfOU5u&ns=ttv-9:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM229:1 Error: Ad adLoadError error: VAST wrapper redirect unwrapping timeout. errorCode: 301(anonymous function) @ VM229:1
2salty.js:325 response received in salty
salty.js:133 - match result code: c1:Kazuya f|c2:Koneko EX|w:1|s:obs|p:a|t:U|m:U|o:1:1.3|t:150
salty.js:325 response received in salty
salty.js:199 - number of:: chars: 3332, matches: 3067, bettors: 5976
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Buntaro EX VS Xiayu) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 0)  ::  unweighted (red W:L)(blue W:L) -> (0:0)(0:0)  ::  details (red W:L)(blue W:L) -> (:)(:)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 9.58:9.58), W:L(P1)(P2)-> (0:0)(0:0), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 2
strategy.js:48 - betting at level: 2, confidence: 32.45
tracker.js:88 AGGRO multiplier active, increasing bet to 3250
salty.js:325 response received in salty
salty.js:133 - match result code: c1:Buntaro EX|c2:Xiayu|w:1|s:cs|p:t|t:A|m:m|o:1:3.8|t:108
salty.js:199 - number of:: chars: 3334, matches: 3068, bettors: 5978
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Sauri VS Lloyd irving) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (50 : 50)  ::  unweighted (red W:L)(blue W:L) -> (1:0)(1:1)  ::  details (red W:L)(blue W:L) -> (A:)(A:X)
strategy.js:504 » predicted odds -> (1.00 : 4.04    )  ::  avg win time (red:blue) -> (135 : 162      )
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 10.52:8.98), W:L(P1)(P2)-> (1:0)(1:1), 
--> dropping confidence by 30%
strategy.js:48 - betting at level: 2, confidence: 35.61
tracker.js:88 AGGRO multiplier active, increasing bet to 3570
salty.js:210 - records saved, matches this cycle: 3
salty.js:133 - match result code: c1:Sauri|c2:Lloyd irving|w:1|s:cs|p:f|t:A|m:m|o:1:7.4|t:93
salty.js:199 - number of:: chars: 3334, matches: 3069, bettors: 5981
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Drdoom VS S_youmu) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 0)  ::  unweighted (red W:L)(blue W:L) -> (0:2)(0:0)  ::  details (red W:L)(blue W:L) -> (:SS)(:)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 9.58:9.58), W:L(P1)(P2)-> (0:2)(0:0), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 4
strategy.js:48 - betting at level: 2, confidence: 32.45
tracker.js:88 AGGRO multiplier active, increasing bet to 3250
salty.js:133 - match result code: c1:Drdoom|c2:S_youmu|w:1|s:cs|p:t|t:S|m:m|o:1:5|t:90
salty.js:199 - number of:: chars: 3335, matches: 3070, bettors: 5982
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Mech.hisui 404 VS Raidou EX) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 100)  ::  unweighted (red W:L)(blue W:L) -> (0:0)(1:1)  ::  details (red W:L)(blue W:L) -> (:)(A:A)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 0.00:19.17), W:L(P1)(P2)-> (0:0)(1:1), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 5
strategy.js:48 - betting at level: 2, confidence: 64.91
tracker.js:88 AGGRO multiplier active, increasing bet to 6500
salty.js:133 - match result code: c1:Mech.hisui 404|c2:Raidou EX|w:0|s:cs|p:f|t:S|m:m|o:4.2:1|t:138
salty.js:199 - number of:: chars: 3336, matches: 3071, bettors: 5983
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Haoumaru VS Nao EX3) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 100)  ::  unweighted (red W:L)(blue W:L) -> (0:1)(1:1)  ::  details (red W:L)(blue W:L) -> (:S)(U:S)
strategy.js:504 » predicted odds -> (1.00 : 11.69   )  ::    ::  avg loss time (red:blue) -> (105 : 105      )
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 0.00:19.24), W:L(P1)(P2)-> (0:1)(1:1), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 6
strategy.js:48 - betting at level: 2, confidence: 65.17
tracker.js:88 AGGRO multiplier active, increasing bet to 6520
salty.js:406 - settings updated, aggro: false
salty.js:133 - match result code: c1:Haoumaru|c2:Nao EX3|w:0|s:cs|p:f|t:S|m:m|o:1:11.5|t:66
salty.js:199 - number of:: chars: 3336, matches: 3072, bettors: 5986
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Sumeragi kuon VS Alice smt) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (100 : 0)  ::  unweighted (red W:L)(blue W:L) -> (2:3)(0:1)  ::  details (red W:L)(blue W:L) -> (SS:SSS)(:S)
strategy.js:504 » predicted odds -> (94.86 : 1.00   )  ::    ::  avg loss time (red:blue) -> (153 : 99       )
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 19.49:0.00), W:L(P1)(P2)-> (2:3)(0:1), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 7
strategy.js:48 - betting at level: 2, confidence: 66.01
salty.js:396 - changing strategy to Scientist
salty.js:406 - settings saved
salty.js:133 - match result code: c1:Sumeragi kuon|c2:Alice smt|w:0|s:cs|p:t|t:S|m:m|o:3:1|t:114
salty.js:199 - number of:: chars: 3336, matches: 3073, bettors: 5987
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Nana diclonius VS S.sinclair) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 100)  ::  unweighted (red W:L)(blue W:L) -> (0:1)(1:2)  ::  details (red W:L)(blue W:L) -> (:S)(S:SS)
strategy.js:504 » predicted odds -> (1.00 : 2.79    )  ::    ::  avg loss time (red:blue) -> (216 : 141      )
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 0.25:19.24), W:L(P1)(P2)-> (0:1)(1:2), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 8
strategy.js:48 - betting at level: 2, confidence: 65.17
salty.js:133 - match result code: c1:Nana diclonius|c2:S.sinclair|w:1|s:cs|p:t|t:S|m:m|o:1:12.5|t:81
salty.js:199 - number of:: chars: 3336, matches: 3074, bettors: 5987
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Jazu EX3 VS Devo the cursed) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (100 : 0)  ::  unweighted (red W:L)(blue W:L) -> (1:1)(0:0)  ::  details (red W:L)(blue W:L) -> (S:S)(:)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 19.17:0.00), W:L(P1)(P2)-> (1:1)(0:0), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 9
strategy.js:48 - betting at level: 2, confidence: 64.91
salty.js:133 - match result code: c1:Jazu EX3|c2:Devo the cursed|w:0|s:cs|p:t|t:S|m:m|o:1:1.3|t:96
salty.js:199 - number of:: chars: 3337, matches: 3075, bettors: 5988
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Jhons lee VS Shin gouki EX2) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (100 : 0)  ::  unweighted (red W:L)(blue W:L) -> (1:2)(0:0)  ::  details (red W:L)(blue W:L) -> (B:B (Requested by Yajirobe) (exhibitions) <a href="http://www.saltybet.com" target="_blank">www.saltybet.com</a>)(:)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 9.58:9.58), W:L(P1)(P2)-> (1:2)(0:0), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 10
strategy.js:48 - betting at level: 2, confidence: 32.45
salty.js:133 - match result code: c1:Jhons lee|c2:Shin gouki EX2|w:0|s:cs|p:f|t:B|m:m|o:2.2:1|t:99
salty.js:199 - number of:: chars: 3338, matches: 3076, bettors: 5990
strategy.js:498 

strategy.js:499 » PREDICTION STATS for (Maebara_keiichi VS Tukuyo) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (0 : 100)  ::  unweighted (red W:L)(blue W:L) -> (0:0)(1:0)  ::  details (red W:L)(blue W:L) -> (:)(S:)
strategy.js:509 

strategy.js:536 -- PROBLEMS:
- insufficient information (scores: 0.00:19.17), W:L(P1)(P2)-> (0:0)(1:0), 
--> dropping confidence by 30%
salty.js:210 - records saved, matches this cycle: 11
strategy.js:48 - betting at level: 2, confidence: 64.91`

**Comment by theCreator111** [comment]
Here are pastebin's of my exported files also in case they are needed:

Records: http://pastebin.com/RSD9HEeS

Chromosomes: http://pastebin.com/BdQB3ncW

I don't know if it has something to do with me updating the genetic weights, the UI is quite confusing to me. I did hit the update button in order to see my winrate with the script now that it has 6k games under its belt.



Also as a side note, I don't know if this is another known issue or my fault - occasionally on refresh the script changes to monk mode and will not change back to scientist even though this is my preferred mode.

**Comment by reconman** [comment]
Have you read synkarius' guide for using saltbot [here](http://explosionduck.com/wp/so-you-want-to-use-saltbot/)?

Looks like you had activated aggro mode which multiplies all your bets by 10. The first error message in the console is a little bug which will be fixed soon. All other error messages are from saltybet itself.

Saltbot will always act as Monk on the first bet after a reload. After it has observed one match it will change to the specified mode. So for example if you selected Scientist and reloaded the site it would say "Monk does not bet" for the first bet and then bet in scientist mode.

Your chromosome looks a bit "weak" to me. You should let the genetic weights update for about 100 generations to get a good betting behaviour. g(10) in the text field means it calculated 10 generations so you should let it run until you see a g(100). You can also update the weights multiple times like 3 times for 35 generations each and it will produce the same results.

You've said that you have 6000 matchup data but according to your posted log you are still missing lots of character data. HotPotSoup and I have uploaded loads of matchup data you could import. They are in the two zip files.

**Comment by theCreator111** [comment]
I have read the guide but I still find it quite confusing. I haven't touched the UI (besides today) in the 6 days or so that I have had the script running because I was worried about losing data.

Could you explain the process behind calculating generations as the console provides no information and all that is apparent is a number slowly increasing up to 100.

How often should I update the genetic weights?

finally, since I am here I would like to ask about the 'stop at' feature and setting custom bet amounts. Does the stop at feature stop when you reach X, or stop betting above X? If the former, is there a way to specify a cap amount you would like to bet? 

I ask because if I go into a losing streak of 4-5 games when the confidence is high or across 10 or so matches the payout has been too low due to ratios I feel too heavily punished now that my confidence is in it's 40s, 50s and sometimes 60s.

I apologize for the messy response, I feel like there is no information anywhere to study elsewhere and I have had to try and figure things out alone.

**Comment by reconman** [comment]
It calculates new chromosome by something called genetic algorithm. In each generation a number of chromosomes is randomly generated. The best of them are mixed with each other to produce new chromosomes.

The best chromosome in the generation is used as new chromosome and the top 5 of the generation is used as new parents (= chromosomes to be mixed with other chromosomes) for the next generation.

If you only have little matchup data you should update the weights every 100 or so but if you have more than 30k you only need to update them every 5000 generations or so. It won't have a huge impact on the betting behaviour if you don't do it.

The "Stop betting at" is a limit as to what the maximum amount of salt you want to win is. If you specify 10k it will stop after reaching 10k or more salt.

Your last question about betting less than the normal betting level can be solved with a multiplier as requested in #79. Also make sure you don't have the aggro mode enabled.

**Comment by theCreator111** [comment]
thank you for the information. It has been very useful.
