### ISSUE TITLE
Tournament mode aggro

### ISSUE THREAD

**Issue by theCreator111** [synkarius/saltbot#87]
During tournaments I've noticed that with aggro mode off the script tones down on the all-in heaviness during tournaments. It would be nice to see it step up the amount only for tournament mode.

I have started leaving it to collect data for days on end and I'd like to see how well I would've done in tournaments (like a winning streak)

in short: allow aggro (T) mode or something of the sorts so normal earnings are unaffected.

**Comment by reconman** [comment]
I was also thinking about this as the betting amount has been reduced to mostly 50-70 % in tournaments since I changed how the betting weights are distributed.

**Comment by AlienLogic** [comment]
Unless I'm misremembering the bot used to always all in during tourneys? I have won tourneys using the new system though, perhaps all-inning until 100k or some other limit would be preferable.
