### ISSUE TITLE
Matchmaking matches registering as exhibitions

### ISSUE THREAD

**Issue by AlienLogic** [synkarius/saltbot#88]
Every now and again I see a matchmaking match register in the db as an exhibition. It pulls the characters correctly and seems to bet properly, but registers the tier as an exhibition. See [this](http://i.imgur.com/wXLOnoK.jpg).

I copied the console output a couple times I happened to be watching:

» PREDICTION STATS for (Rei-kugo VS Wild woody) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (56 : 44)
::  unweighted (red W:L)(blue W:L) -> (10:5)(9:6)
::  details (red W:L)(blue W:L) -> (AAAAAAAAAA:AAABA)(AAAUAAAAA:AUAAA (Requested by StabbyhandsJack) 
(exhibitions) <a href="http://www.saltybet.com" target="_blank">www.saltybet.com</a>)
strategy.js:504 » predicted odds -> (NaN : NaN      )
::  avg win time (red:blue) -> (114 : 148      )  ::  avg loss time (red:blue) -> (130 : 122      )
strategy.js:509
strategy.js:48 - betting at level: 6, confidence: 49.84

» PREDICTION STATS for (Serika VS Toyohime EX2) »
strategy.js:500 » WINS/LOSSES:     weighted totals as % (red:blue) -> (61 : 39)
::  unweighted (red W:L)(blue W:L) -> (8:7)(5:10)  ::  details (red W:L)(blue W:L) -> (BBUBBAAA:AAAAAAA)(AUAAA:AAAAAUASA (Requested by StabbyhandsJack)
(exhibitions) <a href="http://www.saltybet.com" target="_blank">www.saltybet.com</a>)
strategy.js:504 » predicted odds -> (NaN : NaN      )
::  avg win time (red:blue) -> (91 : 152       )  ::  avg loss time (red:blue) -> (124 : 80       )
strategy.js:509 
strategy.js:48 - betting at level: 6, confidence: 49.84

**Comment by reconman** [comment]
The "(Requested by StabbyhandsJack) (exhibitions)" isn't even in the source code. How can it be in your console message?

**Comment by AlienLogic** [comment]
No clue. I have a few more pages in my match db with the same thing, see [here](http://i.imgur.com/5B8SOpe.jpg) and [here](http://i.imgur.com/2IMzgii.jpg).

**Comment by reconman** [comment]
Thank you very much for the screenshots. I don't run saltbot in exhibition mode anymore so I didn't notice the bug. "Requested by" should have never been saved into the tier info. My next commit fixes the issue.

**Comment by AlienLogic** [comment]
I have exhibition betting turned off as well. As far as I've noticed at least, all of these were normal matchmaking matches, if that wasn't clear from my original post.

**Comment by AlienLogic** [comment]
I have exhibition betting turned off as well. As far as I've noticed at least, all of these were normal matchmaking matches, if that wasn't clear from my original post.

**Comment by reconman** [comment]
Make sure to clean the "Requested by x" matches from your data as it saved that text as tier information. Whenever the characters with that text in their tier information fights it will display that string.

That's the only issue I can see from your logs. The console message right after the match is over with all the character, tier, mode, time and odd information would be very helpful to see if it really saves them as exhibitions instead of matchmaking matches. t:m would mean that it saved the matches correcty while t:e means that it does indeed save them as exhibition matches.

**Comment by AlienLogic** [comment]
Unfortunately I didn't save the post-match console messages. I'll do that if I notice the problem from now on.

What would be the easiest way to prune the affected matches from my data?

**Comment by reconman** [comment]
I think I know the cause of why matchmaking tiers were set to the same values for 20+ matches. The twitch chat stopped working so saltbot always used the last message's tier which was the incorrectly detected (requested by x).

I've removed that part of the code and now nothing can cause that bug again.
