### ISSUE TITLE
Plugin refuses to bet at all

### ISSUE THREAD

**Issue by tomiesz** [synkarius/saltbot#93]
Whenever i try to select a mode it comes up with an error in the background and doesn't do anything 
![image](https://cloud.githubusercontent.com/assets/9768508/15271118/3ce039ae-1a3a-11e6-9f52-f4b3fe1804bc.png)

**Comment by reconman** [comment]
I'm more interested in the logs of the main window instead of the popup logs. I've fixed the minor bug causing all those 'farewell' error logs but the main problem is still there.

I can't reproduce the bug without any additional info.

**Comment by synkarius** [comment]
@tomiesz Please read the [Bug Reporting Guide](https://github.com/synkarius/saltbot/blob/master/doc/bugs.MD). It's short.
