### ISSUE TITLE
Plug in errors and now won't work at all

### ISSUE THREAD

**Issue by mobpsycho100** [synkarius/saltbot#95]
Hello. I recently downloaded the saltybot on chrome. I received the following errors:

emberchat-895813e….js:31 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://www.saltybet.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

Failed to load resource: net::ERR_FAILED
No cast extension found

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

After my internet went down then back up again Saltybot refused to work at all now. No Twitch popup, nothing but this:
Uncaught TypeError: Cannot read property 'name' of undefined
326 Uncaught TypeError: Cannot read property 'name' of undefined

I logged in and out and even cleaned cache and it still won't work. I was running monk, then cowboy when I noticed it was only picking blue, so I went back to monk before it stopped working completely. I imported the zip file as well.

**Comment by reconman** [comment]
> emberchat-895813e….js:31 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://www.saltybet.com". The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
> 
> Failed to load resource: net::ERR_FAILED
> No cast extension found
> 
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Those are errors from saltybet itself and have no impact on saltbot whatsoever.

Did you try restarting chrome and visiting saltybet without restoring the previous saltybet tab?

Please post more details on the Uncaught TypeError. Without a script name (displayed on the right) I can't even look up the portion of the code which threw an error.

**Comment by mobpsycho100** [comment]
![saltybet](https://cloud.githubusercontent.com/assets/19557906/15530130/228e37c8-2218-11e6-8e55-5e856a5ee730.png)

![saltybet 2](https://cloud.githubusercontent.com/assets/19557906/15530142/3732b122-2218-11e6-98ff-1061db8faddd.png)

Tried restarting and it's still grayed out.

**Comment by reconman** [comment]
As I've said most of the error messages are there even if you don't have saltbot installed.

On your screenshots I can only the see the first few messages of the saltbot which look normal.

So the saltbot button is grayed out all the time on the saltybet tab? It is always grayed out on the twitch.tv tab just so you know. If it really is grayed out then go to the chrome extension window, activate developer mode on the top, click on "Background page" and view the console there. Please tell me what kind of messages you can see.

**Comment by mobpsycho100** [comment]
![saltybet3](https://cloud.githubusercontent.com/assets/19557906/15551154/4a90d8ae-227a-11e6-92eb-3507b00048a0.png)
![saltybet4](https://cloud.githubusercontent.com/assets/19557906/15551156/4dac7d22-227a-11e6-829d-d234e5a2044b.png)

Tried disabling extensions even though I had no problem with the ones I have active before.

**Comment by reconman** [comment]
Is the symbol grayed out even on saltybet?

For the logs click on "background page (inactive)" instead of details. Then go to the tab console and post a screenshot of the messages there.

**Comment by mobpsycho100** [comment]
When I click on background page (inactive) nothing shows up? Am I doing something wrong?

It's grayed out even on saltybet. The twitch tab doesn't open when I go on saltybet either.

**Comment by reconman** [comment]
Just press F12 on the blank page and you'll get to the console. It is normal that the page is blank.

Do you have a Google or Skype account so I can help you more quickly?

**Comment by mobpsycho100** [comment]
I have google. Do you want me to post it here?

**Comment by reconman** [comment]
Yes, please post your google email so we can do a hangout chat.

**Comment by mobpsycho100** [comment]
harvestmoonbuddies@gmail.com
![saltybet5](https://cloud.githubusercontent.com/assets/19557906/15555800/f1e2ab72-228f-11e6-9ee2-b536856d03a4.png)

**Comment by reconman** [comment]
I've invited you to a Hangout chat.

**Comment by supersalty** [comment]
been having similar issue lately, just greys out on saltybet and have to restart chrome completely for it work again (unload from taskbar too). Not sure when it occurs.

**Comment by mobpsycho100** [comment]
Supersalty through the help of reconman and trial and error I managed to get it work. I had to clean my cache and import the right record files. So far it's working good but it's a wait and see. If I have any other issues I'll make a new post instead of posting in this old thread.
