### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by theCreator111** [synkarius/saltbot#96]
Hello I have data from 20th March till 4th May (when I got sick of leaving my computer on 24/7) **NO EXHIB MATCHES BTW**

Where can I upload it so it can be shared?

It was sporting a 64% win rate till it became upset night and the chromosomes appear to prioritize those results. It's roughly 115k records if you include the ones that were found on the website.

**Comment by reconman** [comment]
Hello theCreator111!

Please upload the file to any file sharer, Google Drive or Dropbox.

I will then publish it here.

**Comment by theCreator111** [comment]
Here is the records with the one from front page.: https://www.dropbox.com/s/qi84244zyd8hdoe/The%20creator%20-%20records.txt?dl=

And here is my records alone: https://www.dropbox.com/s/zy9fuu5j8w7uuns/The%20creator%20-%20records%20NO%20IMPORTs.txt?dl=0

**Comment by reconman** [comment]
Thank you very much!
