### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by jossimo** [synkarius/saltbot#98]
Hi! Been having a blast with your bot, thank you. 
It stopped working several days ago, was working fine for about a week straight but now getting errors and does not function.
Will import my records, chromosome, and reset pool fine but get following errors when trying to update generic weights and clicking scientist mode. No modes work and get similar errors to ones below. Thanks for any help! 
want to add I have tried removing and reinstalling extension from app store to no avail...

extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:255:30)
    at Simulator.evalMutations (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:180:23)
    at HTMLDivElement.<anonymous> (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:505:13)handler @ extensions::uncaught_exception_handler:8
popup.js:74 Object
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'farewell' of undefined
    at chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:39:24

**Comment by reconman** [comment]
Cannot read property length of undefined means that it doesn't have any matches. Can you please upload your chromosome and match data and post links to them here?

Another thing I want you to check is whether you get any error messages when you go to the match data site. (table icon in the extension)

I think I know what the potential problem is but I can't say for sure without match data.

**Comment by reconman** [comment]
And by the way, if you import chromsomes you don't need to reset the pool. You just need to update the chromsome. Resetting the pool resets the chromosome to default values.

**Comment by jossimo** [comment]
The extension icon since yesterday is now grayed out so I can't check for errors when going to match data. Will post links to my current data files. Thanks!

**Comment by jossimo** [comment]
[chromosome--2016-6-11-10.45.txt](https://github.com/synkarius/saltbot/files/315315/chromosome--2016-6-11-10.45.txt)
CHROMOSOME DATA

**Comment by jossimo** [comment]
Error when trying to get match data below.

VM194 extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'concat' of undefined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/matchdata.js:40:19)
    at chrome-extension://bholoegapebhflljekancpcnajigaiih/matchdata.js:22:22handler @ VM194 extensions::uncaught_exception_handler:8(anonymous function) @ VM194 extensions::uncaught_exception_handler:100safeCallbackApply @ VM195 extensions::sendRequest:23handleResponse @ VM195 extensions::sendRequest:74

**Comment by reconman** [comment]
The issue was with the character named The manticore, the queen, and the dragon. Normally commas are replaced because  they would mess up the export and import of records. I used the wrong replace which only replaced the first comma in the name but that character has 2 commas.

You can fix the problem temporarily by opening your match data file, replacing "The manticore_ the queen, and the dragon" with "The manticore_ the queen_ and the dragon". When the new version of saltbot is uploaded that character won't create any more problems.

**Comment by jossimo** [comment]
Awesome, thank you so much!
